New custom iops ranges added and test cases updated
kubernetes-sigs/ibm-vpc-block-csi-driver pull request #201
Opened 2024-11-04 09:08 UTC by MeetanshiGupta

New custom iops ranges added and test cases updated.

2024-11-25 11:49 UTC, sameshai commented on pkg/ibmcsidriver/controller_helper_test.go
> -			requestSize:    20,
Instead of modifying the existing use cases , add use cases for all new ranges.

2024-11-25 11:49 UTC, prankulmahajan requested changes

2024-11-25 11:49 UTC, prankulmahajan commented on vendor/github.com/IBM/ibm-csi-common/pkg/utils/constants.go
> +	MaximumVolumeSizeInBytes int64 = 16 * 1024 * GiB //16000GB = 16TB
This should be taken up automatically by updating the vendor. Instead create PR in csi-common and update the release in go.mod

2024-11-25 11:49 UTC, sameshai requested changes
Add new Cases in UTs

2024-11-25 11:55 UTC, sameshai commented
> Negative test cases
> 
> 1. 150iops 2000GB
> 
> ```
> vasudha@Vasudhas-MacBook-Pro ibm-vpc-block-csi-driver % cat mysc_150iops.yaml
> allowVolumeExpansion: true
> apiVersion: storage.k8s.io/v1
> kind: StorageClass
> metadata:
>   annotations:
>     armada-service: addon-vpc-block-csi-driver
>     kubectl.kubernetes.io/last-applied-configuration: |
>       {"allowVolumeExpansion":true,"apiVersion":"storage.k8s.io/v1","kind":"StorageClass","metadata":{"annotations":{"armada-service":"addon-vpc-block-csi-driver","razee.io/build-url":"https://travis.ibm.com/alchemy-containers/addon-vpc-block-csi-driver/builds/28230890","razee.io/source-url":"https://github.ibm.com/alchemy-containers/addon-vpc-block-csi-driver/commit/e779cb44dffe48ea4725922fea772eb698c66856","version":"5.1.29_642"},"labels":{"addonmanager.kubernetes.io/mode":"Reconcile","app":"ibm-vpc-block-csi-driver","razee/force-apply":"true"},"name":"ibmc-vpc-block-custom"},"parameters":{"billingType":"hourly","classVersion":"1","csi.storage.k8s.io/fstype":"ext4","encrypted":"false","encryptionKey":"","iops":"400","profile":"custom","region":"","resourceGroup":"","tags":"","zone":""},"provisioner":"vpc.block.csi.ibm.io","reclaimPolicy":"Delete"}
>     razee.io/build-url: https://travis.ibm.com/alchemy-containers/addon-vpc-block-csi-driver/builds/28230890
>     razee.io/source-url: https://github.ibm.com/alchemy-containers/addon-vpc-block-csi-driver/commit/e779cb44dffe48ea4725922fea772eb698c66856
>     version: 5.1.29_642
>   creationTimestamp: "2024-11-21T10:49:15Z"
>   labels:
>     addonmanager.kubernetes.io/mode: Reconcile
>     app: ibm-vpc-block-csi-driver
>     razee/force-apply: "true"
>   name: ibmc-vpc-block-custom-150iops
>   resourceVersion: "9048"
>   uid: 8c12122b-2af9-4981-9075-87d795dfa8fc
> parameters:
>   billingType: hourly
>   classVersion: "1"
>   csi.storage.k8s.io/fstype: ext4
>   encrypted: "false"
>   encryptionKey: ""
>   iops: "150"
>   profile: custom
>   region: ""
>   resourceGroup: ""
>   tags: ""
>   zone: ""
> provisioner: vpc.block.csi.ibm.io
> reclaimPolicy: Delete
> volumeBindingMode: Immediate
> vasudha@Vasudhas-MacBook-Pro ibm-vpc-block-csi-driver % kubectl create -f mysc_150iops.yaml
> storageclass.storage.k8s.io/ibmc-vpc-block-custom-150iops created
> vasudha@Vasudhas-MacBook-Pro ibm-vpc-block-csi-driver %  kubectl create -f pvc_150iops.yaml
> persistentvolumeclaim/pvc2000 created
> vasudha@Vasudhas-MacBook-Pro ibm-vpc-block-csi-driver % kubectl get pvc                    
> NAME      STATUS    VOLUME   CAPACITY   ACCESS MODES   STORAGECLASS                    VOLUMEATTRIBUTESCLASS   AGE
> pvc2000   Pending                                      ibmc-vpc-block-custom-150iops   <unset>                 6s
> vasudha@Vasudhas-MacBook-Pro ibm-vpc-block-csi-driver % kubectl describe pvc pvc2000       
> Name:          pvc2000
> Namespace:     default
> StorageClass:  ibmc-vpc-block-custom-150iops
> Status:        Pending
> Volume:        
> Labels:        <none>
> Annotations:   volume.beta.kubernetes.io/storage-provisioner: vpc.block.csi.ibm.io
>                volume.kubernetes.io/storage-provisioner: vpc.block.csi.ibm.io
> Finalizers:    [kubernetes.io/pvc-protection]
> Capacity:      
> Access Modes:  
> VolumeMode:    Filesystem
> Used By:       <none>
> Events:
>   Type     Reason                Age               From                                                                                                     Message
>   ----     ------                ----              ----                                                                                                     -------
>   Warning  ProvisioningFailed    12s               vpc.block.csi.ibm.io_ibm-vpc-block-csi-controller-0_5fc28df6-ddb0-4a57-b842-d5aca677e3d7                 failed to provision volume with StorageClass "ibmc-vpc-block-custom-150iops": rpc error: code = Internal desc = {RequestID: fa34648d-d97e-4bdc-ab12-bbab2063f057 , Code: InternalError, Description: Internal error occurred%!(EXTRA string=creation), BackendError: {Code:FailedToPlaceOrder, Type:ProvisioningFailed, Description:Failed to create volume with the storage provider, BackendError:Trace Code:fa34648d-d97e-4bdc-ab12-bbab2063f057, The volume profile specified in the request is not valid for the provided capacity and/or IOPS. Please check , RC:500}, Action: Please check 'BackendError' tag for more details}
>   Warning  ProvisioningFailed    11s               vpc.block.csi.ibm.io_ibm-vpc-block-csi-controller-86cfdd45f8-mbgqz_9952877d-78af-4e6f-80f3-13dbe8a70574  failed to provision volume with StorageClass "ibmc-vpc-block-custom-150iops": rpc error: code = Internal desc = {RequestID: 247a5c48-732d-4ec9-be52-7aeddf5cab88 , Code: InternalError, Description: Internal error occurred%!(EXTRA string=creation), BackendError: {Code:FailedToPlaceOrder, Type:ProvisioningFailed, Description:Failed to create volume with the storage provider, BackendError:Trace Code:247a5c48-732d-4ec9-be52-7aeddf5cab88, The volume profile specified in the request is not valid for the provided capacity and/or IOPS. Please check , RC:500}, Action: Please check 'BackendError' tag for more details}
>   Warning  ProvisioningFailed    11s               vpc.block.csi.ibm.io_ibm-vpc-block-csi-controller-0_5fc28df6-ddb0-4a57-b842-d5aca677e3d7                 failed to provision volume with StorageClass "ibmc-vpc-block-custom-150iops": rpc error: code = Internal desc = {RequestID: d3bb5172-ceb0-495a-bc0c-9f7a3934b239 , Code: InternalError, Description: Internal error occurred%!(EXTRA string=creation), BackendError: {Code:FailedToPlaceOrder, Type:ProvisioningFailed, Description:Failed to create volume with the storage provider, BackendError:Trace Code:d3bb5172-ceb0-495a-bc0c-9f7a3934b239, The volume profile specified in the request is not valid for the provided capacity and/or IOPS. Please check , RC:500}, Action: Please check 'BackendError' tag for more details}
>   Warning  ProvisioningFailed    10s               vpc.block.csi.ibm.io_ibm-vpc-block-csi-controller-86cfdd45f8-mbgqz_9952877d-78af-4e6f-80f3-13dbe8a70574  failed to provision volume with StorageClass "ibmc-vpc-block-custom-150iops": rpc error: code = Internal desc = {RequestID: bfe1040d-1930-4ab3-b8eb-c908608b1118 , Code: InternalError, Description: Internal error occurred%!(EXTRA string=creation), BackendError: {Code:FailedToPlaceOrder, Type:ProvisioningFailed, Description:Failed to create volume with the storage provider, BackendError:Trace Code:bfe1040d-1930-4ab3-b8eb-c908608b1118, The volume profile specified in the request is not valid for the provided capacity and/or IOPS. Please check , RC:500}, Action: Please check 'BackendError' tag for more details}
>   Normal   ExternalProvisioning  8s (x2 over 14s)  persistentvolume-controller                                                                              Waiting for a volume to be created either by the external provisioner 'vpc.block.csi.ibm.io' or manually by the system administrator. If volume creation is delayed, please verify that the provisioner is running and correctly registered.
>   Warning  ProvisioningFailed    8s                vpc.block.csi.ibm.io_ibm-vpc-block-csi-controller-0_5fc28df6-ddb0-4a57-b842-d5aca677e3d7                 failed to provision volume with StorageClass "ibmc-vpc-block-custom-150iops": rpc error: code = Internal desc = {RequestID: 4954b753-591c-43de-b677-acb4c4eee4fa , Code: InternalError, Description: Internal error occurred%!(EXTRA string=creation), BackendError: {Code:FailedToPlaceOrder, Type:ProvisioningFailed, Description:Failed to create volume with the storage provider, BackendError:Trace Code:4954b753-591c-43de-b677-acb4c4eee4fa, The volume profile specified in the request is not valid for the provided capacity and/or IOPS. Please check , RC:500}, Action: Please check 'BackendError' tag for more details}
>   Warning  ProvisioningFailed    8s                vpc.block.csi.ibm.io_ibm-vpc-block-csi-control [...]

2024-11-25 18:11 UTC, spzala commented
/easycla

2024-11-27 14:07 UTC, sameshai requested changes
@MeetanshiGupta @vasudha786 I see that The cases you verified are actually hitting the code and error is coming from backend.

The range code you have modified is throwing different error and it can be verified only through secrets in storage class

https://github.com/kubernetes-sigs/ibm-vpc-block-csi-driver/tree/master/examples/kubernetes#storageclass-secret

2024-11-28 05:55 UTC, closed without merging