New block custom iops ranges added and test cases updated
kubernetes-sigs/ibm-vpc-block-csi-driver pull request #203
Opened 2024-11-28 05:43 UTC by MeetanshiGupta

New block custom iops ranges added, test cases updated and MaximumBlockVolumeDiskSizeInGb variable added.
GHE Issue - [https://github.ibm.com/alchemy-containers/armada-storage/issues/6768](https://github.ibm.com/alchemy-containers/armada-storage/issues/6768)

2024-11-28 06:01 UTC, sameshai requested changes
Please add MaximumBlockVolumeDiskSizeInGb in driver constants. Let remove dependancy on ibm-csi-common

2024-11-28 06:04 UTC, prankulmahajan commented
/ok-to-test

2024-11-28 06:31 UTC, prankulmahajan commented
@MeetanshiGupta Please remove changes from vendor dir. Also can you fix the failed tests

2024-11-28 06:42 UTC, sameshai reviewed
Code Changes looks good , please post the results with volume storage class secret for each new range then we should be good

2024-11-28 07:55 UTC, arahamad reviewed
@MeetanshiGupta , Can you upload the test results

2024-11-28 09:31 UTC, vasudha786 commented
With Secret - Positive test cases

1. 300iops 3000GiB
```
vasudha@Vasudhas-MacBook-Pro ibm-vpc-block-csi-driver % cat sc.yaml
allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ibmc-vpc-block-custom-iops-test
parameters:
  billingType: hourly
  classVersion: "1"
  csi.storage.k8s.io/fstype: ext4
  csi.storage.k8s.io/provisioner-secret-name: test1
  csi.storage.k8s.io/provisioner-secret-namespace: kube-system
  profile: custom
  encrypted: "true"
  encryptionKey: ""
provisioner: vpc.block.csi.ibm.io
reclaimPolicy: Delete
volumeBindingMode: Immediate%                                                                                                                         vasudha@Vasudhas-MacBook-Pro ibm-vpc-block-csi-driver % cat pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test1
spec:
  storageClassName: ibmc-vpc-block-custom-iops-test
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3000Gi%                                                                                                                                
vasudha@Vasudhas-MacBook-Pro ibm-vpc-block-csi-driver % cat secret.yaml
apiVersion: v1
kind: Secret
type: vpc.block.csi.ibm.io
metadata:
  name: test1
  namespace: kube-system
stringData:
  iops: "300"%  
vasudha@Vasudhas-MacBook-Pro ibm-vpc-block-csi-driver % kubectl apply -f secret.yaml               
secret/test1 created
vasudha@Vasudhas-MacBook-Pro ibm-vpc-block-csi-driver % kubectl apply -f sc.yaml
storageclass.storage.k8s.io/ibmc-vpc-block-custom-iops-test created
vasudha@Vasudhas-MacBook-Pro ibm-vpc-block-csi-driver % kubectl apply -f pvc.yaml
persistentvolumeclaim/test1 created
vasudha@Vasudhas-MacBook-Pro ibm-vpc-block-csi-driver % kubectl get pvc
NAME    STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS                      VOLUMEATTRIBUTESCLASS   AGE
test1   Bound    pvc-2e646959-c8e1-4beb-85fe-859ee101267a   3000Gi     RWO            ibmc-vpc-block-custom-iops-test   <unset>                 80s
```
2. 48000iops 16000GiB
```
vasudha@Vasudhas-MacBook-Pro ibm-vpc-block-csi-driver % cat secret.yaml
apiVersion: v1
kind: Secret
type: vpc.block.csi.ibm.io
metadata:
  name: test1
  namespace: kube-system
stringData:
  iops: "48000"%                                                                                                                                      
vasudha@Vasudhas-MacBook-Pro ibm-vpc-block-csi-driver % cat sc.yaml
allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ibmc-vpc-block-custom-iops-16000
parameters:
  billingType: hourly
  classVersion: "1"
  csi.storage.k8s.io/fstype: ext4
  csi.storage.k8s.io/provisioner-secret-name: test1
  csi.storage.k8s.io/provisioner-secret-namespace: kube-system
  profile: custom
  encrypted: "true"
  encryptionKey: ""
provisioner: vpc.block.csi.ibm.io
reclaimPolicy: Delete
volumeBindingMode: Immediate%                                                                                                                         vasudha@Vasudhas-MacBook-Pro ibm-vpc-block-csi-driver % cat pvc.yaml 
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test1
spec:
  storageClassName: ibmc-vpc-block-custom-iops-16000
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 16000Gi% 
vasudha@Vasudhas-MacBook-Pro ibm-vpc-block-csi-driver % kubectl apply -f secret.yaml
secret/test1 created
vasudha@Vasudhas-MacBook-Pro ibm-vpc-block-csi-driver % kubectl apply -f sc.yaml    
storageclass.storage.k8s.io/ibmc-vpc-block-custom-iops-16000 created
vasudha@Vasudhas-MacBook-Pro ibm-vpc-block-csi-driver % kubectl apply -f pvc.yaml   
persistentvolumeclaim/test1 created
vasudha@Vasudhas-MacBook-Pro ibm-vpc-block-csi-driver % kubectl get pvc
NAME    STATUS    VOLUME   CAPACITY   ACCESS MODES   STORAGECLASS                       VOLUMEATTRIBUTESCLASS   AGE
test1   Pending                                      ibmc-vpc-block-custom-iops-16000   <unset>                 11s
vasudha@Vasudhas-MacBook-Pro ibm-vpc-block-csi-driver % kubectl get pvc
NAME    STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS                       VOLUMEATTRIBUTESCLASS   AGE
test1   Bound    pvc-befc5872-cc7a-40fe-85d2-84cc873df149   16000Gi    RWO            ibmc-vpc-block-custom-iops-16000   <unset>                 106s
```

3. 1000iops 16000GiB
```
vasudha@Vasudhas-MacBook-Pro ibm-vpc-block-csi-driver % cat secret.yaml
apiVersion: v1
kind: Secret
type: vpc.block.csi.ibm.io
metadata:
  name: test1
  namespace: kube-system
stringData:
  iops: "1000"%                                                                                                                                       
vasudha@Vasudhas-MacBook-Pro ibm-vpc-block-csi-driver % cat sc.yaml
allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ibmc-vpc-block-custom-iops-16000
parameters:
  billingType: hourly
  classVersion: "1"
  csi.storage.k8s.io/fstype: ext4
  csi.storage.k8s.io/provisioner-secret-name: test1
  csi.storage.k8s.io/provisioner-secret-namespace: kube-system
  profile: custom
  encrypted: "true"
  encryptionKey: ""
provisioner: vpc.block.csi.ibm.io
reclaimPolicy: Delete
volumeBindingMode: Immediate%                                                                                                                         vasudha@Vasudhas-MacBook-Pro ibm-vpc-block-csi-driver % cat pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test1
spec:
  storageClassName: ibmc-vpc-block-custom-iops-16000
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 16000Gi% 
vasudha@Vasudhas-MacBook-Pro ibm-vpc-block-csi-driver % kubectl apply -f secret.yaml 
secret/test1 created
vasudha@Vasudhas-MacBook-Pro ibm-vpc-block-csi-driver % kubectl apply -f sc.yaml     
storageclass.storage.k8s.io/ibmc-vpc-block-custom-iops-16000 created
vasudha@Vasudhas-MacBook-Pro ibm-vpc-block-csi-driver % kubectl apply -f pvc.yaml
persistentvolumeclaim/test1 created
vasudha@Vasudhas-MacBook-Pro ibm-vpc-block-csi-driver % kubectl get pvc          
NAME    STATUS    VOLUME   CAPACITY   ACCESS MODES   STORAGECLASS                       VOLUMEATTRIBUTESCLASS   AGE
test1   Pending                                      ibmc-vpc-block-custom-iops-16000   <unset>                 6s
vasudha@Vasudhas-MacBook-Pro ibm-vpc-block-csi-driver % kubectl get pvc
NAME    STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS                       VOLUMEATTRIBUTESCLASS   AGE
test1   Bound    pvc-9a8a7e32-3f0b-4a2b-a999-1506fd50371f   16000Gi    RWO            ibmc-vpc-block-custom-iops-16000   <unset>                 40s
```

4. 40000iops 7999GiB
```
vasudha@Vasudhas-MacBook-Pro ibm-vpc-block-csi-driver % cat secret.yaml
apiVersion: v1
kind: Secret
type: vpc.block.csi.ibm.io
metadata:
  name: test1
  namespace: kube-system
stringData:
  iops: "40000"%                                                                                                                                      
vasudha@Vasudhas-MacBook-Pro ibm-vpc-block-csi-driver % cat sc.yaml    
allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ibmc-vpc-block-custom-iops-7999
parameters:
  billingType: hourly
  classVersion: "1"
  csi.storage.k8s.io/fstype: ext4
  csi.storage.k8s.io/provisioner-secret-name: test1
  csi.storage.k8s.io/provisioner-secret-namespace: kube-system
  profile: custom
  encrypted: "true"
  encryptionKey: ""
provisioner: vpc.block.csi.ibm.io
reclaimPolicy: Delete
volumeBindingMode: Immediate%                                                                                                                         vasudha@Vasudhas-MacBook-Pro ibm-vpc-block-csi-driver % cat pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tes [...]

2024-11-28 09:41 UTC, vasudha786 commented
Without secret - Negative test cases

1) 150iops 2000GiB
```
vasudha@Vasudhas-MacBook-Pro ibm-vpc-block-csi-driver % cat mysc_150iops.yaml
allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    armada-service: addon-vpc-block-csi-driver
    kubectl.kubernetes.io/last-applied-configuration: |
      {"allowVolumeExpansion":true,"apiVersion":"storage.k8s.io/v1","kind":"StorageClass","metadata":{"annotations":{"armada-service":"addon-vpc-block-csi-driver","razee.io/build-url":"https://travis.ibm.com/alchemy-containers/addon-vpc-block-csi-driver/builds/28230890","razee.io/source-url":"https://github.ibm.com/alchemy-containers/addon-vpc-block-csi-driver/commit/e779cb44dffe48ea4725922fea772eb698c66856","version":"5.1.29_642"},"labels":{"addonmanager.kubernetes.io/mode":"Reconcile","app":"ibm-vpc-block-csi-driver","razee/force-apply":"true"},"name":"ibmc-vpc-block-custom"},"parameters":{"billingType":"hourly","classVersion":"1","csi.storage.k8s.io/fstype":"ext4","encrypted":"false","encryptionKey":"","iops":"400","profile":"custom","region":"","resourceGroup":"","tags":"","zone":""},"provisioner":"vpc.block.csi.ibm.io","reclaimPolicy":"Delete"}
    razee.io/build-url: https://travis.ibm.com/alchemy-containers/addon-vpc-block-csi-driver/builds/28230890
    razee.io/source-url: https://github.ibm.com/alchemy-containers/addon-vpc-block-csi-driver/commit/e779cb44dffe48ea4725922fea772eb698c66856
    version: 5.1.29_642
  creationTimestamp: "2024-11-21T10:49:15Z"
  labels:
    addonmanager.kubernetes.io/mode: Reconcile
    app: ibm-vpc-block-csi-driver
    razee/force-apply: "true"
  name: ibmc-vpc-block-custom-150iops
  resourceVersion: "9048"
  uid: 8c12122b-2af9-4981-9075-87d795dfa8fc
parameters:
  billingType: hourly
  classVersion: "1"
  csi.storage.k8s.io/fstype: ext4
  encrypted: "false"
  encryptionKey: ""
  iops: "150"
  profile: custom
  region: ""
  resourceGroup: ""
  tags: ""
  zone: ""
provisioner: vpc.block.csi.ibm.io
reclaimPolicy: Delete
volumeBindingMode: Immediate
vasudha@Vasudhas-MacBook-Pro ibm-vpc-block-csi-driver % kubectl create -f mysc_150iops.yaml
storageclass.storage.k8s.io/ibmc-vpc-block-custom-150iops created
vasudha@Vasudhas-MacBook-Pro ibm-vpc-block-csi-driver %  kubectl create -f pvc_150iops.yaml
persistentvolumeclaim/pvc2000 created
vasudha@Vasudhas-MacBook-Pro ibm-vpc-block-csi-driver % kubectl get pvc                    
NAME      STATUS    VOLUME   CAPACITY   ACCESS MODES   STORAGECLASS                    VOLUMEATTRIBUTESCLASS   AGE
pvc2000   Pending                                      ibmc-vpc-block-custom-150iops   <unset>                 6s
vasudha@Vasudhas-MacBook-Pro ibm-vpc-block-csi-driver % kubectl describe pvc pvc2000       
Name:          pvc2000
Namespace:     default
StorageClass:  ibmc-vpc-block-custom-150iops
Status:        Pending
Volume:        
Labels:        <none>
Annotations:   volume.beta.kubernetes.io/storage-provisioner: vpc.block.csi.ibm.io
               volume.kubernetes.io/storage-provisioner: vpc.block.csi.ibm.io
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:      
Access Modes:  
VolumeMode:    Filesystem
Used By:       <none>
Events:
  Type     Reason                Age               From                                                                                                     Message
  ----     ------                ----              ----                                                                                                     -------
  Warning  ProvisioningFailed    12s               vpc.block.csi.ibm.io_ibm-vpc-block-csi-controller-0_5fc28df6-ddb0-4a57-b842-d5aca677e3d7                 failed to provision volume with StorageClass "ibmc-vpc-block-custom-150iops": rpc error: code = Internal desc = {RequestID: fa34648d-d97e-4bdc-ab12-bbab2063f057 , Code: InternalError, Description: Internal error occurred%!(EXTRA string=creation), BackendError: {Code:FailedToPlaceOrder, Type:ProvisioningFailed, Description:Failed to create volume with the storage provider, BackendError:Trace Code:fa34648d-d97e-4bdc-ab12-bbab2063f057, The volume profile specified in the request is not valid for the provided capacity and/or IOPS. Please check , RC:500}, Action: Please check 'BackendError' tag for more details}
  Warning  ProvisioningFailed    11s               vpc.block.csi.ibm.io_ibm-vpc-block-csi-controller-86cfdd45f8-mbgqz_9952877d-78af-4e6f-80f3-13dbe8a70574  failed to provision volume with StorageClass "ibmc-vpc-block-custom-150iops": rpc error: code = Internal desc = {RequestID: 247a5c48-732d-4ec9-be52-7aeddf5cab88 , Code: InternalError, Description: Internal error occurred%!(EXTRA string=creation), BackendError: {Code:FailedToPlaceOrder, Type:ProvisioningFailed, Description:Failed to create volume with the storage provider, BackendError:Trace Code:247a5c48-732d-4ec9-be52-7aeddf5cab88, The volume profile specified in the request is not valid for the provided capacity and/or IOPS. Please check , RC:500}, Action: Please check 'BackendError' tag for more details}
  Warning  ProvisioningFailed    11s               vpc.block.csi.ibm.io_ibm-vpc-block-csi-controller-0_5fc28df6-ddb0-4a57-b842-d5aca677e3d7                 failed to provision volume with StorageClass "ibmc-vpc-block-custom-150iops": rpc error: code = Internal desc = {RequestID: d3bb5172-ceb0-495a-bc0c-9f7a3934b239 , Code: InternalError, Description: Internal error occurred%!(EXTRA string=creation), BackendError: {Code:FailedToPlaceOrder, Type:ProvisioningFailed, Description:Failed to create volume with the storage provider, BackendError:Trace Code:d3bb5172-ceb0-495a-bc0c-9f7a3934b239, The volume profile specified in the request is not valid for the provided capacity and/or IOPS. Please check , RC:500}, Action: Please check 'BackendError' tag for more details}
  Warning  ProvisioningFailed    10s               vpc.block.csi.ibm.io_ibm-vpc-block-csi-controller-86cfdd45f8-mbgqz_9952877d-78af-4e6f-80f3-13dbe8a70574  failed to provision volume with StorageClass "ibmc-vpc-block-custom-150iops": rpc error: code = Internal desc = {RequestID: bfe1040d-1930-4ab3-b8eb-c908608b1118 , Code: InternalError, Description: Internal error occurred%!(EXTRA string=creation), BackendError: {Code:FailedToPlaceOrder, Type:ProvisioningFailed, Description:Failed to create volume with the storage provider, BackendError:Trace Code:bfe1040d-1930-4ab3-b8eb-c908608b1118, The volume profile specified in the request is not valid for the provided capacity and/or IOPS. Please check , RC:500}, Action: Please check 'BackendError' tag for more details}
  Normal   ExternalProvisioning  8s (x2 over 14s)  persistentvolume-controller                                                                              Waiting for a volume to be created either by the external provisioner 'vpc.block.csi.ibm.io' or manually by the system administrator. If volume creation is delayed, please verify that the provisioner is running and correctly registered.
  Warning  ProvisioningFailed    8s                vpc.block.csi.ibm.io_ibm-vpc-block-csi-controller-0_5fc28df6-ddb0-4a57-b842-d5aca677e3d7                 failed to provision volume with StorageClass "ibmc-vpc-block-custom-150iops": rpc error: code = Internal desc = {RequestID: 4954b753-591c-43de-b677-acb4c4eee4fa , Code: InternalError, Description: Internal error occurred%!(EXTRA string=creation), BackendError: {Code:FailedToPlaceOrder, Type:ProvisioningFailed, Description:Failed to create volume with the storage provider, BackendError:Trace Code:4954b753-591c-43de-b677-acb4c4eee4fa, The volume profile specified in the request is not valid for the provided capacity and/or IOPS. Please check , RC:500}, Action: Please check 'BackendError' tag for more details}
  Warning  ProvisioningFailed    8s                vpc.block.csi.ibm.io_ibm-vpc-block-csi-controller-86cfdd45f8-mbgqz_9952877d-78af-4e6f-80f3-13dbe8a70574  failed to provision volume with StorageClass "ibmc-vpc-block-custo [...]

2024-11-28 09:42 UTC, vasudha786 commented
Without secret - Positive test cases

1) 250iops 2000GiB
```
vasudha@Vasudhas-MacBook-Pro ibm-vpc-block-csi-driver % cat mysc_250iops.yaml                
allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    armada-service: addon-vpc-block-csi-driver
    kubectl.kubernetes.io/last-applied-configuration: |
      {"allowVolumeExpansion":true,"apiVersion":"storage.k8s.io/v1","kind":"StorageClass","metadata":{"annotations":{"armada-service":"addon-vpc-block-csi-driver","razee.io/build-url":"https://travis.ibm.com/alchemy-containers/addon-vpc-block-csi-driver/builds/28230890","razee.io/source-url":"https://github.ibm.com/alchemy-containers/addon-vpc-block-csi-driver/commit/e779cb44dffe48ea4725922fea772eb698c66856","version":"5.1.29_642"},"labels":{"addonmanager.kubernetes.io/mode":"Reconcile","app":"ibm-vpc-block-csi-driver","razee/force-apply":"true"},"name":"ibmc-vpc-block-custom"},"parameters":{"billingType":"hourly","classVersion":"1","csi.storage.k8s.io/fstype":"ext4","encrypted":"false","encryptionKey":"","iops":"400","profile":"custom","region":"","resourceGroup":"","tags":"","zone":""},"provisioner":"vpc.block.csi.ibm.io","reclaimPolicy":"Delete"}
    razee.io/build-url: https://travis.ibm.com/alchemy-containers/addon-vpc-block-csi-driver/builds/28230890
    razee.io/source-url: https://github.ibm.com/alchemy-containers/addon-vpc-block-csi-driver/commit/e779cb44dffe48ea4725922fea772eb698c66856
    version: 5.1.29_642
  creationTimestamp: "2024-11-21T10:49:15Z"
  labels:
    addonmanager.kubernetes.io/mode: Reconcile
    app: ibm-vpc-block-csi-driver
    razee/force-apply: "true"
  name: ibmc-vpc-block-custom-250iops
  resourceVersion: "9048"
  uid: 8c12122b-2af9-4981-9075-87d795dfa8fc
parameters:
  billingType: hourly
  classVersion: "1"
  csi.storage.k8s.io/fstype: ext4
  encrypted: "false"
  encryptionKey: ""
  iops: "250"
  profile: custom
  region: ""
  resourceGroup: ""
  tags: ""
  zone: ""
provisioner: vpc.block.csi.ibm.io
reclaimPolicy: Delete
volumeBindingMode: Immediate
vasudha@Vasudhas-MacBook-Pro ibm-vpc-block-csi-driver % kubectl create -f mysc_250iops.yaml
storageclass.storage.k8s.io/ibmc-vpc-block-custom-250iops created
vasudha@Vasudhas-MacBook-Pro ibm-vpc-block-csi-driver % cat pvc_250iops.yaml              
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc2000
  #name: testpvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2000Gi
  storageClassName: ibmc-vpc-block-custom-250iops
vasudha@Vasudhas-MacBook-Pro ibm-vpc-block-csi-driver % kubectl create -f pvc_250iops.yaml
persistentvolumeclaim/pvc2000 created
vasudha@Vasudhas-MacBook-Pro ibm-vpc-block-csi-driver % kubectl get pvc                   
NAME      STATUS    VOLUME   CAPACITY   ACCESS MODES   STORAGECLASS                    VOLUMEATTRIBUTESCLASS   AGE
pvc2000   Pending                                      ibmc-vpc-block-custom-250iops   <unset>                 14s
vasudha@Vasudhas-MacBook-Pro ibm-vpc-block-csi-driver % kubectl get pvc
NAME      STATUS    VOLUME   CAPACITY   ACCESS MODES   STORAGECLASS                    VOLUMEATTRIBUTESCLASS   AGE
pvc2000   Pending                                      ibmc-vpc-block-custom-250iops   <unset>                 19s
vasudha@Vasudhas-MacBook-Pro ibm-vpc-block-csi-driver % kubectl get pvc
NAME      STATUS    VOLUME   CAPACITY   ACCESS MODES   STORAGECLASS                    VOLUMEATTRIBUTESCLASS   AGE
pvc2000   Pending                                      ibmc-vpc-block-custom-250iops   <unset>                 27s
vasudha@Vasudhas-MacBook-Pro ibm-vpc-block-csi-driver % kubectl get pvc
NAME      STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS                    VOLUMEATTRIBUTESCLASS   AGE
pvc2000   Bound    pvc-6e250a0b-7d5e-4ae8-966a-18b0167517f0   2000Gi     RWO            ibmc-vpc-block-custom-250iops   <unset>                 51s
vasudha@Vasudhas-MacBook-Pro ibm-vpc-block-csi-driver % cat pod.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: testpodrwm
  labels:
    app: testpodrwm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: testpodrwm
  template:
    metadata:
      labels:
        app: testpodrwm
    spec:
      containers:
      - image: rabbitmq:3-management #image name which should be avilable within cluster
        name: rabbitmq # name of the container inside POD
        volumeMounts:
        - mountPath: /myvol  # mount path for pvc from container
          name: pvc-name # pvc name for this pod
      volumes:
      - name: pvc-name  # volume resource name in this POD, user can choose any name as per kubernetes
        persistentVolumeClaim:
          claimName: pvc2000 # pvc name which was created by using claim.yaml file%                                                                                          vasudha@Vasudhas-MacBook-Pro ibm-vpc-block-csi-driver % kubectl create -f pod.yaml                
deployment.apps/testpodrwm created
vasudha@Vasudhas-MacBook-Pro ibm-vpc-block-csi-driver % kubectl get pods
NAME                          READY   STATUS              RESTARTS   AGE
testpodrwm-74b559c465-jvd7v   0/1     ContainerCreating   0          7s
vasudha@Vasudhas-MacBook-Pro ibm-vpc-block-csi-driver % kubectl get pods
NAME                          READY   STATUS    RESTARTS   AGE
testpodrwm-74b559c465-jvd7v   1/1     Running   0          29s
vasudha@Vasudhas-MacBook-Pro ibm-vpc-block-csi-driver % kubectl get deployment
NAME         READY   UP-TO-DATE   AVAILABLE   AGE
testpodrwm   1/1     1            1           52s
vasudha@Vasudhas-MacBook-Pro ibm-vpc-block-csi-driver % kubectl exec -it testpodrwm-74b559c465-jvd7v -- /bin/bash
root@testpodrwm-74b559c465-jvd7v:/# cd myvol/
root@testpodrwm-74b559c465-jvd7v:/myvol# echo "new" > hi.txt
root@testpodrwm-74b559c465-jvd7v:/myvol# cat myvol/hi.txt
cat: myvol/hi.txt: No such file or directory
root@testpodrwm-74b559c465-jvd7v:/myvol# cat hi.txt
new
```

2) 350iops 4000GiB
```
vasudha@Vasudhas-MacBook-Pro ibm-vpc-block-csi-driver % cat mysc_350iops.yaml              
allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    armada-service: addon-vpc-block-csi-driver
    kubectl.kubernetes.io/last-applied-configuration: |
      {"allowVolumeExpansion":true,"apiVersion":"storage.k8s.io/v1","kind":"StorageClass","metadata":{"annotations":{"armada-service":"addon-vpc-block-csi-driver","razee.io/build-url":"https://travis.ibm.com/alchemy-containers/addon-vpc-block-csi-driver/builds/28230890","razee.io/source-url":"https://github.ibm.com/alchemy-containers/addon-vpc-block-csi-driver/commit/e779cb44dffe48ea4725922fea772eb698c66856","version":"5.1.29_642"},"labels":{"addonmanager.kubernetes.io/mode":"Reconcile","app":"ibm-vpc-block-csi-driver","razee/force-apply":"true"},"name":"ibmc-vpc-block-custom"},"parameters":{"billingType":"hourly","classVersion":"1","csi.storage.k8s.io/fstype":"ext4","encrypted":"false","encryptionKey":"","iops":"400","profile":"custom","region":"","resourceGroup":"","tags":"","zone":""},"provisioner":"vpc.block.csi.ibm.io","reclaimPolicy":"Delete"}
    razee.io/build-url: https://travis.ibm.com/alchemy-containers/addon-vpc-block-csi-driver/builds/28230890
    razee.io/source-url: https://github.ibm.com/alchemy-containers/addon-vpc-block-csi-driver/commit/e779cb44dffe48ea4725922fea772eb698c66856
    version: 5.1.29_642
  creationTimestamp: "2024-11-21T10:49:15Z"
  labels:
    addonmanager.kubernetes.io/mode: Reconcile
    app: ibm-vpc-block-csi-driver
    razee/force-apply: "true"
  name: ibmc-vpc-block-custom-350iops
  resourceVersion: "9048"
  uid: 8c12122b-2af9-4981-9075-87d795dfa8fc
parameters:
  billingType: hourly
  classVersion: "1"
  csi.storage.k8s.io/fstype: ext4
  encrypted: "false"
  encryptionKey: ""
  iops: "350"
  profile: custom
  region: ""
  resourceGroup: ""
  tags: ""
  zone: ""
provisioner: vpc.block.csi.ibm.io
reclaimP [...]

2024-11-28 12:23 UTC, vasudha786 commented
With Block add-on and without Secret

vasudha@Vasudhas-MacBook-Pro ibm-vpc-block-csi-driver % cat mysc.yaml
allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    armada-service: addon-vpc-block-csi-driver
    kubectl.kubernetes.io/last-applied-configuration: |
      {"allowVolumeExpansion":true,"apiVersion":"storage.k8s.io/v1","kind":"StorageClass","metadata":{"annotations":{"armada-service":"addon-vpc-block-csi-driver","razee.io/build-url":"https://travis.ibm.com/alchemy-containers/addon-vpc-block-csi-driver/builds/28230890","razee.io/source-url":"https://github.ibm.com/alchemy-containers/addon-vpc-block-csi-driver/commit/e779cb44dffe48ea4725922fea772eb698c66856","version":"5.1.29_642"},"labels":{"addonmanager.kubernetes.io/mode":"Reconcile","app":"ibm-vpc-block-csi-driver","razee/force-apply":"true"},"name":"ibmc-vpc-block-custom"},"parameters":{"billingType":"hourly","classVersion":"1","csi.storage.k8s.io/fstype":"ext4","encrypted":"false","encryptionKey":"","iops":"400","profile":"custom","region":"","resourceGroup":"","tags":"","zone":""},"provisioner":"vpc.block.csi.ibm.io","reclaimPolicy":"Delete"}
    razee.io/build-url: https://travis.ibm.com/alchemy-containers/addon-vpc-block-csi-driver/builds/28230890
    razee.io/source-url: https://github.ibm.com/alchemy-containers/addon-vpc-block-csi-driver/commit/e779cb44dffe48ea4725922fea772eb698c66856
    version: 5.1.29_642
  creationTimestamp: "2024-11-21T10:49:15Z"
  labels:
    addonmanager.kubernetes.io/mode: Reconcile
    app: ibm-vpc-block-csi-driver
    razee/force-apply: "true"
  name: ibmc-vpc-block-custom-48000iops
  resourceVersion: "9048"
  uid: 8c12122b-2af9-4981-9075-87d795dfa8fc
parameters:
  billingType: hourly
  classVersion: "1"
  csi.storage.k8s.io/fstype: ext4
  encrypted: "false"
  encryptionKey: ""
  iops: "48000"
  profile: custom
  region: ""
  resourceGroup: ""
  tags: ""
  zone: ""
provisioner: vpc.block.csi.ibm.io
reclaimPolicy: Delete
volumeBindingMode: Immediate
vasudha@Vasudhas-MacBook-Pro ibm-vpc-block-csi-driver % cat mypvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc16000
  #name: testpvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 16000Gi
  storageClassName: ibmc-vpc-block-custom-48000iops% 
vasudha@Vasudhas-MacBook-Pro ibm-vpc-block-csi-driver % kubectl apply -f mysc.yaml
storageclass.storage.k8s.io/ibmc-vpc-block-custom-48000iops created
vasudha@Vasudhas-MacBook-Pro ibm-vpc-block-csi-driver % kubectl apply -f mypvc.yaml
persistentvolumeclaim/pvc16000 created
vasudha@Vasudhas-MacBook-Pro ibm-vpc-block-csi-driver % kubectl get pvc               
NAME       STATUS    VOLUME   CAPACITY   ACCESS MODES   STORAGECLASS                      VOLUMEATTRIBUTESCLASS   AGE
pvc16000   Pending                                      ibmc-vpc-block-custom-48000iops   <unset>                 9s
vasudha@Vasudhas-MacBook-Pro ibm-vpc-block-csi-driver % kubectl get pvc
NAME       STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS                      VOLUMEATTRIBUTESCLASS   AGE
pvc16000   Bound    pvc-a70ed360-1772-415e-8721-1211bb22c0d9   16000Gi    RWO            ibmc-vpc-block-custom-48000iops   <unset>                 37s

2024-11-28 12:23 UTC, vasudha786 commented
With Block add-on and with Secret

vasudha@Vasudhas-MacBook-Pro ibm-vpc-block-csi-driver % cat secret.yaml
apiVersion: v1
kind: Secret
type: vpc.block.csi.ibm.io
metadata:
  name: test1
  namespace: kube-system
stringData:
  iops: "48000"%                                                                                                    
vasudha@Vasudhas-MacBook-Pro ibm-vpc-block-csi-driver % cat sc.yaml
allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ibmc-vpc-block-custom-iops-16000
parameters:
  billingType: hourly
  classVersion: "1"
  csi.storage.k8s.io/fstype: ext4
  csi.storage.k8s.io/provisioner-secret-name: test1
  csi.storage.k8s.io/provisioner-secret-namespace: kube-system
  profile: custom
  encrypted: "true"
  encryptionKey: ""
provisioner: vpc.block.csi.ibm.io
reclaimPolicy: Delete
volumeBindingMode: Immediate%                                                                                       
vasudha@Vasudhas-MacBook-Pro ibm-vpc-block-csi-driver % cat pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test1
spec:
  storageClassName: ibmc-vpc-block-custom-iops-16000
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 16000Gi%
vasudha@Vasudhas-MacBook-Pro ibm-vpc-block-csi-driver % kubectl apply -f secret.yaml  
secret/test1 created
vasudha@Vasudhas-MacBook-Pro ibm-vpc-block-csi-driver % kubectl apply -f sc.yaml    
storageclass.storage.k8s.io/ibmc-vpc-block-custom-iops-16000 created
vasudha@Vasudhas-MacBook-Pro ibm-vpc-block-csi-driver % kubectl apply -f pvc.yaml
persistentvolumeclaim/test1 created
vasudha@Vasudhas-MacBook-Pro ibm-vpc-block-csi-driver % kubectl get pvc          
NAME    STATUS    VOLUME   CAPACITY   ACCESS MODES   STORAGECLASS                       VOLUMEATTRIBUTESCLASS   AGE
test1   Pending                                      ibmc-vpc-block-custom-iops-16000   <unset>                 10s
vasudha@Vasudhas-MacBook-Pro ibm-vpc-block-csi-driver % kubectl describe pvc test1
Name:          test1
Namespace:     default
StorageClass:  ibmc-vpc-block-custom-iops-16000
Status:        Pending
Volume:        
Labels:        <none>
Annotations:   volume.beta.kubernetes.io/storage-provisioner: vpc.block.csi.ibm.io
               volume.kubernetes.io/storage-provisioner: vpc.block.csi.ibm.io
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:      
Access Modes:  
VolumeMode:    Filesystem
Used By:       <none>
Events:
  Type     Reason                Age                From                                                                                      Message
  ----     ------                ----               ----                                                                                      -------
  Warning  ProvisioningFailed    25s                vpc.block.csi.ibm.io_ibm-vpc-block-csi-controller-0_f068970d-fbe0-420f-99bc-fabd58a0b47a  failed to provision volume with StorageClass "ibmc-vpc-block-custom-iops-16000": rpc error: code = InvalidArgument desc = {RequestID: ce4ecbba-8501-4869-b25b-5c122f144617 , Code: InvalidParameters, Description: Failed to extract parameters, BackendError: invalid PVC size for custom class: <16000>. Should be in range [10 - 2048]GiB, Action: Please provide valid parameters}
  Warning  ProvisioningFailed    24s                vpc.block.csi.ibm.io_ibm-vpc-block-csi-controller-0_f068970d-fbe0-420f-99bc-fabd58a0b47a  failed to provision volume with StorageClass "ibmc-vpc-block-custom-iops-16000": rpc error: code = InvalidArgument desc = {RequestID: 90364f6f-91d0-4d99-965e-032848372546 , Code: InvalidParameters, Description: Failed to extract parameters, BackendError: invalid PVC size for custom class: <16000>. Should be in range [10 - 2048]GiB, Action: Please provide valid parameters}
  Warning  ProvisioningFailed    22s                vpc.block.csi.ibm.io_ibm-vpc-block-csi-controller-0_f068970d-fbe0-420f-99bc-fabd58a0b47a  failed to provision volume with StorageClass "ibmc-vpc-block-custom-iops-16000": rpc error: code = InvalidArgument desc = {RequestID: c7cfada2-e259-42fe-9bca-15e1c89029d7 , Code: InvalidParameters, Description: Failed to extract parameters, BackendError: invalid PVC size for custom class: <16000>. Should be in range [10 - 2048]GiB, Action: Please provide valid parameters}
  Warning  ProvisioningFailed    18s                vpc.block.csi.ibm.io_ibm-vpc-block-csi-controller-0_f068970d-fbe0-420f-99bc-fabd58a0b47a  failed to provision volume with StorageClass "ibmc-vpc-block-custom-iops-16000": rpc error: code = InvalidArgument desc = {RequestID: 99497d5a-05bb-4137-90c7-1ed7645680e0 , Code: InvalidParameters, Description: Failed to extract parameters, BackendError: invalid PVC size for custom class: <16000>. Should be in range [10 - 2048]GiB, Action: Please provide valid parameters}
  Normal   ExternalProvisioning  13s (x2 over 25s)  persistentvolume-controller                                                               Waiting for a volume to be created either by the external provisioner 'vpc.block.csi.ibm.io' or manually by the system administrator. If volume creation is delayed, please verify that the provisioner is running and correctly registered.
  Normal   Provisioning          10s (x5 over 25s)  vpc.block.csi.ibm.io_ibm-vpc-block-csi-controller-0_f068970d-fbe0-420f-99bc-fabd58a0b47a  External provisioner is provisioning volume for claim "default/test1"
  Warning  ProvisioningFailed    10s                vpc.block.csi.ibm.io_ibm-vpc-block-csi-controller-0_f068970d-fbe0-420f-99bc-fabd58a0b47a  failed to provision volume with StorageClass "ibmc-vpc-block-custom-iops-16000": rpc error: code = InvalidArgument desc = {RequestID: 0e1cfee5-7013-4877-8fea-a8afce327242 , Code: InvalidParameters, Description: Failed to extract parameters, BackendError: invalid PVC size for custom class: <16000>. Should be in range [10 - 2048]GiB, Action: Please provide valid parameters}

2024-11-28 14:20 UTC, sameshai approved these changes

2024-11-29 05:19 UTC, prankulmahajan commented
/lgtm

2024-11-29 06:29 UTC, arahamad requested changes
@MeetanshiGupta , lets make it uniform between storage class and storage class secret, may be batter to remove validation check

2024-11-29 11:19 UTC, sameshai requested changes
Please fix the test cases , remove the validation for iops from the test cases from TestOverrideParams

```
{
			testCaseName: "Secret invalid IOPS for custom class",
			request: &csi.CreateVolumeRequest{Name: volumeName, CapacityRange: &csi.CapacityRange{RequiredBytes: 11811160064, LimitBytes: utils.MinimumVolumeSizeInBytes + utils.MinimumVolumeSizeInBytes},
				Parameters: map[string]string{Profile: "custom",
					Zone:          "testzone",
					Region:        "us-south-test",
					Tag:           "test",
					ResourceGroup: "myresourcegroups",
					Encrypted:     "false",
					EncryptionKey: "123",
					IOPS:          noIops,
				},
				Secrets: map[string]string{
					IOPS: secretInvalidIops,
				},
			},
			expectedVolume: &provider.Volume{Name: &volumeName,
				Capacity:  &volumeSize,
				VPCVolume: provider.VPCVolume{Profile: &provider.Profile{Name: "custom"}},
			},
			expectedStatus: false,
			expectedError:  fmt.Errorf("%v:<%v> invalid value", IOPS, secretInvalidIops),
		},
```

2024-11-29 12:52 UTC, sameshai approved these changes
/ok-to-test

2024-11-29 13:37 UTC, vasudha786 commented
Recent testing of negative changes via secret 

1) 16000GiB 49000iops
```
vasudha@Vasudhas-MacBook-Pro ibm-vpc-block-csi-driver % kubectl apply -f secret.yaml 
secret/test1 created
vasudha@Vasudhas-MacBook-Pro ibm-vpc-block-csi-driver % kubectl apply -f sc.yaml                                           
storageclass.storage.k8s.io/ibmc-vpc-block-custom-iops-16000 created
vasudha@Vasudhas-MacBook-Pro ibm-vpc-block-csi-driver % kubectl apply -f pvc.yaml    
persistentvolumeclaim/test1 created
vasudha@Vasudhas-MacBook-Pro ibm-vpc-block-csi-driver % kubectl get pvc              
NAME    STATUS    VOLUME   CAPACITY   ACCESS MODES   STORAGECLASS                       VOLUMEATTRIBUTESCLASS   AGE
test1   Pending                                      ibmc-vpc-block-custom-iops-16000   <unset>                 12s
vasudha@Vasudhas-MacBook-Pro ibm-vpc-block-csi-driver % kubectl describe pvc test1
Name:          test1
Namespace:     default
StorageClass:  ibmc-vpc-block-custom-iops-16000
Status:        Pending
Volume:        
Labels:        <none>
Annotations:   volume.beta.kubernetes.io/storage-provisioner: vpc.block.csi.ibm.io
               volume.kubernetes.io/storage-provisioner: vpc.block.csi.ibm.io
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:      
Access Modes:  
VolumeMode:    Filesystem
Used By:       <none>
Events:
  Type     Reason                Age               From                                                                                                     Message
  ----     ------                ----              ----                                                                                                     -------
  Warning  ProvisioningFailed    17s               vpc.block.csi.ibm.io_ibm-vpc-block-csi-controller-56c5c6964f-xhclf_4ce6a88a-c053-477d-bed5-1bee9868e4ee  failed to provision volume with StorageClass "ibmc-vpc-block-custom-iops-16000": rpc error: code = Internal desc = {RequestID: 765e9e24-8023-43e7-855d-f96a9e91980c , Code: InternalError, Description: Internal error occurred%!(EXTRA string=creation), BackendError: {Code:FailedToPlaceOrder, Type:ProvisioningFailed, Description:Failed to create volume with the storage provider, BackendError:Trace Code:765e9e24-8023-43e7-855d-f96a9e91980c, The volume profile specified in the request is not valid for the provided capacity and/or IOPS. Please check , RC:500}, Action: Please check 'BackendError' tag for more details}
  Warning  ProvisioningFailed    16s               vpc.block.csi.ibm.io_ibm-vpc-block-csi-controller-56c5c6964f-xhclf_4ce6a88a-c053-477d-bed5-1bee9868e4ee  failed to provision volume with StorageClass "ibmc-vpc-block-custom-iops-16000": rpc error: code = Internal desc = {RequestID: 35841593-46b2-442b-83da-bf5530b70752 , Code: InternalError, Description: Internal error occurred%!(EXTRA string=creation), BackendError: {Code:FailedToPlaceOrder, Type:ProvisioningFailed, Description:Failed to create volume with the storage provider, BackendError:Trace Code:35841593-46b2-442b-83da-bf5530b70752, The volume profile specified in the request is not valid for the provided capacity and/or IOPS. Please check , RC:500}, Action: Please check 'BackendError' tag for more details}
  Warning  ProvisioningFailed    13s               vpc.block.csi.ibm.io_ibm-vpc-block-csi-controller-56c5c6964f-xhclf_4ce6a88a-c053-477d-bed5-1bee9868e4ee  failed to provision volume with StorageClass "ibmc-vpc-block-custom-iops-16000": rpc error: code = Internal desc = {RequestID: b411a5f9-f969-43c4-9bbf-376e9f9561a6 , Code: InternalError, Description: Internal error occurred%!(EXTRA string=creation), BackendError: {Code:FailedToPlaceOrder, Type:ProvisioningFailed, Description:Failed to create volume with the storage provider, BackendError:Trace Code:b411a5f9-f969-43c4-9bbf-376e9f9561a6, The volume profile specified in the request is not valid for the provided capacity and/or IOPS. Please check , RC:500}, Action: Please check 'BackendError' tag for more details}
  Normal   ExternalProvisioning  9s (x2 over 18s)  persistentvolume-controller                                                                              Waiting for a volume to be created either by the external provisioner 'vpc.block.csi.ibm.io' or manually by the system administrator. If volume creation is delayed, please verify that the provisioner is running and correctly registered.
  Warning  ProvisioningFailed    9s                vpc.block.csi.ibm.io_ibm-vpc-block-csi-controller-56c5c6964f-xhclf_4ce6a88a-c053-477d-bed5-1bee9868e4ee  failed to provision volume with StorageClass "ibmc-vpc-block-custom-iops-16000": rpc error: code = Internal desc = {RequestID: 52add7f1-2e42-4eaf-9f8f-be11b796e174 , Code: InternalError, Description: Internal error occurred%!(EXTRA string=creation), BackendError: {Code:FailedToPlaceOrder, Type:ProvisioningFailed, Description:Failed to create volume with the storage provider, BackendError:Trace Code:52add7f1-2e42-4eaf-9f8f-be11b796e174, The volume profile specified in the request is not valid for the provided capacity and/or IOPS. Please check , RC:500}, Action: Please check 'BackendError' tag for more details}
  Normal   Provisioning          1s (x5 over 18s)  vpc.block.csi.ibm.io_ibm-vpc-block-csi-controller-56c5c6964f-xhclf_4ce6a88a-c053-477d-bed5-1bee9868e4ee  External provisioner is provisioning volume for claim "default/test1"
  Warning  ProvisioningFailed    1s                vpc.block.csi.ibm.io_ibm-vpc-block-csi-controller-56c5c6964f-xhclf_4ce6a88a-c053-477d-bed5-1bee9868e4ee  failed to provision volume with StorageClass "ibmc-vpc-block-custom-iops-16000": rpc error: code = Internal desc = {RequestID: 1c54171d-7d0e-46ce-a686-1450f19a8e4f , Code: InternalError, Description: Internal error occurred%!(EXTRA string=creation), BackendError: {Code:FailedToPlaceOrder, Type:ProvisioningFailed, Description:Failed to create volume with the storage provider, BackendError:Trace Code:1c54171d-7d0e-46ce-a686-1450f19a8e4f, The volume profile specified in the request is not valid for the provided capacity and/or IOPS. Please check , RC:500}, Action: Please check 'BackendError' tag for more details}
vasudha@Vasudhas-MacBook-Pro ibm-vpc-block-csi-driver % cat secret.yaml
apiVersion: v1
kind: Secret
type: vpc.block.csi.ibm.io
metadata:
  name: test1
  namespace: kube-system
stringData:
  iops: "49000"%                                                                                                                                         
vasudha@Vasudhas-MacBook-Pro ibm-vpc-block-csi-driver % cat sc.yaml    
allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ibmc-vpc-block-custom-iops-16000
parameters:
  billingType: hourly
  classVersion: "1"
  csi.storage.k8s.io/fstype: ext4
  csi.storage.k8s.io/provisioner-secret-name: test1
  csi.storage.k8s.io/provisioner-secret-namespace: kube-system
  profile: custom
  encrypted: "true"
  encryptionKey: ""
provisioner: vpc.block.csi.ibm.io
reclaimPolicy: Delete
volumeBindingMode: Immediate%                                                                                                                            vasudha@Vasudhas-MacBook-Pro ibm-vpc-block-csi-driver % cat pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test1
spec:
  storageClassName: ibmc-vpc-block-custom-iops-16000
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 16000Gi% 
```

2) 16000GiB 950iops
```
vasudha@Vasudhas-MacBook-Pro ibm-vpc-block-csi-driver % kubectl apply -f sc.yaml 
storageclass.storage.k8s.io/ibmc-vpc-block-custom-iops-16000 created
vasudha@Vasudhas-MacBook-Pro ibm-vpc-block-csi-driver % kubectl apply -f secret.yaml
secret/test1 created
vasudha@Vasudhas-MacBook-Pro ibm-vpc-block-csi-driver % kubectl apply -f pvc.yaml   
persistentvolumeclaim/test1 created
vasudha@Vasudhas-MacBook-Pro ibm-vpc-block-csi-driver % kubectl get pvc
NAME    STATUS    VOLUME   CAPACITY   ACCESS MODES   STORAGECLASS  [...]

2024-11-29 13:50 UTC, vasudha786 commented
Testing of positive test cases via secret

1. 1000iops 16000GiB
```
vasudha@Vasudhas-MacBook-Pro ibm-vpc-block-csi-driver % cat secret.yaml
apiVersion: v1
kind: Secret
type: vpc.block.csi.ibm.io
metadata:
  name: test1
  namespace: kube-system
stringData:
  iops: "1000"%                                                                                                                                       
vasudha@Vasudhas-MacBook-Pro ibm-vpc-block-csi-driver % cat sc.yaml
allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ibmc-vpc-block-custom-iops-16000
parameters:
  billingType: hourly
  classVersion: "1"
  csi.storage.k8s.io/fstype: ext4
  csi.storage.k8s.io/provisioner-secret-name: test1
  csi.storage.k8s.io/provisioner-secret-namespace: kube-system
  profile: custom
  encrypted: "true"
  encryptionKey: ""
provisioner: vpc.block.csi.ibm.io
reclaimPolicy: Delete
volumeBindingMode: Immediate%                                                                                                                         vasudha@Vasudhas-MacBook-Pro ibm-vpc-block-csi-driver % cat pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test1
spec:
  storageClassName: ibmc-vpc-block-custom-iops-16000
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 16000Gi% 
vasudha@Vasudhas-MacBook-Pro ibm-vpc-block-csi-driver % kubectl apply -f secret.yaml 
secret/test1 created
vasudha@Vasudhas-MacBook-Pro ibm-vpc-block-csi-driver % kubectl apply -f sc.yaml     
storageclass.storage.k8s.io/ibmc-vpc-block-custom-iops-16000 created
vasudha@Vasudhas-MacBook-Pro ibm-vpc-block-csi-driver % kubectl apply -f pvc.yaml
persistentvolumeclaim/test1 created
vasudha@Vasudhas-MacBook-Pro ibm-vpc-block-csi-driver % kubectl get pvc          
NAME    STATUS    VOLUME   CAPACITY   ACCESS MODES   STORAGECLASS                       VOLUMEATTRIBUTESCLASS   AGE
test1   Pending                                      ibmc-vpc-block-custom-iops-16000   <unset>                 6s
vasudha@Vasudhas-MacBook-Pro ibm-vpc-block-csi-driver % kubectl get pvc
NAME    STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS                       VOLUMEATTRIBUTESCLASS   AGE
test1   Bound    pvc-9a8a7e32-3f0b-4a2b-a999-1506fd50371f   16000Gi    RWO            ibmc-vpc-block-custom-iops-16000   <unset>                 40s
```

2. 40000iops 7999GiB
```
vasudha@Vasudhas-MacBook-Pro ibm-vpc-block-csi-driver % cat secret.yaml
apiVersion: v1
kind: Secret
type: vpc.block.csi.ibm.io
metadata:
  name: test1
  namespace: kube-system
stringData:
  iops: "40000"%                                                                                                                                      
vasudha@Vasudhas-MacBook-Pro ibm-vpc-block-csi-driver % cat sc.yaml    
allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ibmc-vpc-block-custom-iops-7999
parameters:
  billingType: hourly
  classVersion: "1"
  csi.storage.k8s.io/fstype: ext4
  csi.storage.k8s.io/provisioner-secret-name: test1
  csi.storage.k8s.io/provisioner-secret-namespace: kube-system
  profile: custom
  encrypted: "true"
  encryptionKey: ""
provisioner: vpc.block.csi.ibm.io
reclaimPolicy: Delete
volumeBindingMode: Immediate%                                                                                                                         vasudha@Vasudhas-MacBook-Pro ibm-vpc-block-csi-driver % cat pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test1
spec:
  storageClassName: ibmc-vpc-block-custom-iops-7999
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 7999Gi% 
vasudha@Vasudhas-MacBook-Pro ibm-vpc-block-csi-driver % kubectl apply -f secret.yaml
secret/test1 created
vasudha@Vasudhas-MacBook-Pro ibm-vpc-block-csi-driver % kubectl apply -f sc.yaml    
storageclass.storage.k8s.io/ibmc-vpc-block-custom-iops-7999 created
vasudha@Vasudhas-MacBook-Pro ibm-vpc-block-csi-driver % kubectl apply -f pvc.yaml
persistentvolumeclaim/test1 created
vasudha@Vasudhas-MacBook-Pro ibm-vpc-block-csi-driver % kubectl get pvc
NAME    STATUS    VOLUME   CAPACITY   ACCESS MODES   STORAGECLASS                      VOLUMEATTRIBUTESCLASS   AGE
test1   Pending                                      ibmc-vpc-block-custom-iops-7999   <unset>                 21s
vasudha@Vasudhas-MacBook-Pro ibm-vpc-block-csi-driver % kubectl get pvc
NAME    STATUS    VOLUME   CAPACITY   ACCESS MODES   STORAGECLASS                      VOLUMEATTRIBUTESCLASS   AGE
test1   Pending                                      ibmc-vpc-block-custom-iops-7999   <unset>                 26s
vasudha@Vasudhas-MacBook-Pro ibm-vpc-block-csi-driver % kubectl get pvc
NAME    STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS                      VOLUMEATTRIBUTESCLASS   AGE
test1   Bound    pvc-d6a9c34e-88bc-4f67-a3eb-8c2d8876be7c   7999Gi     RWO            ibmc-vpc-block-custom-iops-7999   <unset>                 53s

```
3. 48000iops 9999GiB
```
vasudha@Vasudhas-MacBook-Pro ibm-vpc-block-csi-driver % cat secret.yaml
apiVersion: v1
kind: Secret
type: vpc.block.csi.ibm.io
metadata:
  name: test1
  namespace: kube-system
stringData:
  iops: "48000"%                                                                                                                                      
vasudha@Vasudhas-MacBook-Pro ibm-vpc-block-csi-driver % cat sc.yaml    
allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ibmc-vpc-block-custom-iops-9999
parameters:
  billingType: hourly
  classVersion: "1"
  csi.storage.k8s.io/fstype: ext4
  csi.storage.k8s.io/provisioner-secret-name: test1
  csi.storage.k8s.io/provisioner-secret-namespace: kube-system
  profile: custom
  encrypted: "true"
  encryptionKey: ""
provisioner: vpc.block.csi.ibm.io
reclaimPolicy: Delete
volumeBindingMode: Immediate%                                                                                                                         vasudha@Vasudhas-MacBook-Pro ibm-vpc-block-csi-driver % cat pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test1
spec:
  storageClassName: ibmc-vpc-block-custom-iops-9999
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 9999Gi%  
vasudha@Vasudhas-MacBook-Pro ibm-vpc-block-csi-driver % kubectl apply -f secret.yaml
secret/test1 created
vasudha@Vasudhas-MacBook-Pro ibm-vpc-block-csi-driver % kubectl apply -f sc.yaml    
storageclass.storage.k8s.io/ibmc-vpc-block-custom-iops-9999 created
vasudha@Vasudhas-MacBook-Pro ibm-vpc-block-csi-driver % kubectl apply -f pvc.yaml
persistentvolumeclaim/test1 created
vasudha@Vasudhas-MacBook-Pro ibm-vpc-block-csi-driver % kubectl get pvc           
NAME    STATUS    VOLUME   CAPACITY   ACCESS MODES   STORAGECLASS                      VOLUMEATTRIBUTESCLASS   AGE
test1   Pending                                      ibmc-vpc-block-custom-iops-9999   <unset>                 11s
vasudha@Vasudhas-MacBook-Pro ibm-vpc-block-csi-driver % kubectl get pvc
NAME    STATUS    VOLUME   CAPACITY   ACCESS MODES   STORAGECLASS                      VOLUMEATTRIBUTESCLASS   AGE
test1   Pending                                      ibmc-vpc-block-custom-iops-9999   <unset>                 24s
vasudha@Vasudhas-MacBook-Pro ibm-vpc-block-csi-driver % kubectl get pvc
NAME    STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS                      VOLUMEATTRIBUTESCLASS   AGE
test1   Bound    pvc-b68686fb-c717-4eab-bc3c-b4398e82382e   9999Gi     RWO            ibmc-vpc-block-custom-iops-9999   <unset>                 53s
```

2024-11-29 14:04 UTC, arahamad approved these changes
/lgtm

please verify before releasing it

2024-11-29 14:12 UTC, merged