fix nil reference
kubernetes-sigs/ibm-vpc-block-csi-driver pull request #29
Opened 2021-09-07 06:59 UTC by ambiknai

This fixes the exception for nil reference while creating a PVC

2021-09-07 07:26 UTC, ambiknai commented
`TEST RESULT`

```
root@devmachine1:~/WORKSPACE/src/github.com/kubernetes-sigs/ibm-vpc-block-csi-driver# oc get pods -n kube-system | grep block
ibm-vpc-block-csi-controller-0                 1/5     CrashLoopBackOff   4348       3d22h
ibm-vpc-block-csi-node-lhzr5                   3/3     Running            0          3d22h
ibm-vpc-block-csi-node-qxf7d                   3/3     Running            0          3d22h
ibm-vpc-block-csi-node-rxsqj                   3/3     Running            0          3d22h
root@devmachine1:~/WORKSPACE/src/github.com/kubernetes-sigs/ibm-vpc-block-csi-driver# oc delete pod -n kube-system ibm-vpc-block-csi-controller-0 
pod "ibm-vpc-block-csi-controller-0" deleted
root@devmachine1:~/WORKSPACE/src/github.com/kubernetes-sigs/ibm-vpc-block-csi-driver# oc get pvc
NAME                 STATUS    VOLUME   CAPACITY   ACCESS MODES   STORAGECLASS                AGE
csi-block-pvc-good   Pending                                      ibmc-vpc-block-5iops-tier   3d22h
root@devmachine1:~/WORKSPACE/src/github.com/kubernetes-sigs/ibm-vpc-block-csi-driver# oc get pods -n kube-system | grep block
ibm-vpc-block-csi-controller-0                 0/5     ContainerCreating   0          9s
ibm-vpc-block-csi-node-lhzr5                   3/3     Running             0          3d22h
ibm-vpc-block-csi-node-qxf7d                   3/3     Running             0          3d22h
ibm-vpc-block-csi-node-rxsqj                   3/3     Running             0          3d22h
root@devmachine1:~/WORKSPACE/src/github.com/kubernetes-sigs/ibm-vpc-block-csi-driver# oc get pods -n kube-system | grep block
ibm-vpc-block-csi-controller-0                 5/5     Running   0          71s
ibm-vpc-block-csi-node-lhzr5                   3/3     Running   0          3d22h
ibm-vpc-block-csi-node-qxf7d                   3/3     Running   0          3d22h
ibm-vpc-block-csi-node-rxsqj                   3/3     Running   0          3d22h
root@devmachine1:~/WORKSPACE/src/github.com/kubernetes-sigs/ibm-vpc-block-csi-driver# oc get pvc
NAME                 STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS                AGE
csi-block-pvc-good   Bound    pvc-f681406a-7fa0-4451-b15f-b30e37ff48f8   10Gi       RWO            ibmc-vpc-block-5iops-tier   3d22h
root@devmachine1:~/WORKSPACE/src/github.com/kubernetes-sigs/ibm-vpc-block-csi-driver# 
```

2021-09-07 08:25 UTC, arahamad requested changes

2021-09-07 08:25 UTC, arahamad commented on pkg/ibmcsidriver/controller.go
> +				return createCSIVolumeResponse(*existingVol, int64(*(existingVol.Capacity)*utils.GB), nil, csiCS.CSIProvider.GetClusterInfo().ClusterID), nil
Can you optimise this call to avoid calling createCSIVolumeResponse method multiple time

2021-09-07 08:25 UTC, arahamad commented on pkg/ibmcsidriver/controller.go
> +		return createCSIVolumeResponse(*volumeObj, int64(*(requestedVolume.Capacity)*utils.GB), nil, csiCS.CSIProvider.GetClusterInfo().ClusterID), nil
Can you optimise this call to avoid calling createCSIVolumeResponse method multiple time

2021-09-07 09:44 UTC, ambiknai commented
```
"level":"info","ts":"2021-09-07T09:42:14.243Z","caller":"ibmcsidriver/identity.go:83","msg":"CSIIdentityServer-Probe...","RequestID":"50dd4764-1914-474e-ac73-09800875ac59","Request":{}}
I0907 09:42:14.243567       1 server.go:157] GRPC response: 
root@devmachine1:~/WORKSPACE/src/github.com/kubernetes-sigs/ibm-vpc-block-csi-driver# oc describe pod testpodrwo-749774548d-nbjgl
Name:               testpodrwo-749774548d-nbjgl
Namespace:          default
Priority:           0
PriorityClassName:  <none>
Node:               sat-ocp-workernode01/10.242.0.5
Start Time:         Tue, 07 Sep 2021 01:24:47 -0700
Labels:             app=testpodrwo
                    pod-template-hash=749774548d
Annotations:        cni.projectcalico.org/podIP: 172.30.27.224/32
                    cni.projectcalico.org/podIPs: 172.30.27.224/32
                    k8s.v1.cni.cncf.io/network-status:
                      [{
                          "name": "",
                          "ips": [
                              "172.30.27.224"
                          ],
                          "default": true,
                          "dns": {}
                      }]
                    k8s.v1.cni.cncf.io/networks-status:
                      [{
                          "name": "",
                          "ips": [
                              "172.30.27.224"
                          ],
                          "default": true,
                          "dns": {}
                      }]
Status:             Running
IP:                 172.30.27.224
Controlled By:      ReplicaSet/testpodrwo-749774548d
Containers:
  container-name:
    Container ID:   cri-o://75cefbfab43a05311f49ceb3734ada3ff8df327d50343f6e5fb61a3035f53cd4
    Image:          rabbitmq
    Image ID:       docker.io/library/rabbitmq@sha256:0de00994f3b05cb05d7fdd6edb526be9cbd3a633e12176b4d5f127b0b14e0b9d
    Port:           <none>
    Host Port:      <none>
    State:          Running
      Started:      Tue, 07 Sep 2021 02:42:26 -0700
    Ready:          True
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /myvolumepath from pvc-name (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-gs6s2 (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             True 
  ContainersReady   True 
  PodScheduled      True 
Volumes:
  pvc-name:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  csi-block-pvc-good
    ReadOnly:   false
  default-token-gs6s2:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-gs6s2
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason                  Age                   From                           Message
  ----     ------                  ----                  ----                           -------
  Normal   Scheduled               78m                   default-scheduler              Successfully assigned default/testpodrwo-749774548d-nbjgl to sat-ocp-workernode01
  Warning  FailedAttachVolume      6m18s (x43 over 77m)  attachdetach-controller        AttachVolume.Attach failed for volume "pvc-f681406a-7fa0-4451-b15f-b30e37ff48f8" : rpc error: code = Unavailable desc = transport is closing
  Warning  FailedMount             3m55s (x8 over 69m)   kubelet, sat-ocp-workernode01  Unable to attach or mount volumes: unmounted volumes=[pvc-name], unattached volumes=[default-token-gs6s2 pvc-name]: timed out waiting for the condition
  Normal   SuccessfulAttachVolume  2m14s                 attachdetach-controller        AttachVolume.Attach succeeded for volume "pvc-f681406a-7fa0-4451-b15f-b30e37ff48f8"
  Warning  FailedMount             99s (x26 over 76m)    kubelet, sat-ocp-workernode01  Unable to attach or mount volumes: unmounted volumes=[pvc-name], unattached volumes=[pvc-name default-token-gs6s2]: timed out waiting for the condition
  Normal   AddedInterface          77s                   multus                         Add eth0 [172.30.27.224/32]
  Normal   Pulling                 77s                   kubelet, sat-ocp-workernode01  Pulling image "rabbitmq"
  Normal   Pulled                  67s                   kubelet, sat-ocp-workernode01  Successfully pulled image "rabbitmq" in 10.191832164s
  Normal   Created                 66s                   kubelet, sat-ocp-workernode01  Created container container-name
  Normal   Started                 66s                   kubelet, sat-ocp-workernode01  Started container container-name
root@devmachine1:~/WORKSPACE/src/github.com/kubernetes-sigs/ibm-vpc-block-csi-driver# oc get pods
NAME                          READY   STATUS    RESTARTS   AGE
testpodrwo-749774548d-nbjgl   1/1     Running   0          78m
root@devmachine1:~/WORKSPACE/src/github.com/kubernetes-sigs/ibm-vpc-block-csi-driver# oc exec -it testpodrwo-749774548d-nbjgl /bin/bash
root@testpodrwo-749774548d-nbjgl:/# mount
overlay on / type overlay (rw,relatime,context="system_u:object_r:container_file_t:s0:c409,c725",lowerdir=/var/data/criorootstorage/overlay/l/6D7TEGIMLRAQYIBGMM4RL2BG2K:/var/data/criorootstorage/overlay/l/ZAYO3WJO54PVN6WL2ZY73FOJKK:/var/data/criorootstorage/overlay/l/WMF4PJCWBOE7PPPG53MOVJBPN2:/var/data/criorootstorage/overlay/l/GSUIYY6I5WTTSV62NUMCDGMOAL:/var/data/criorootstorage/overlay/l/7APMAEYMU4X7E2M23NQNCID7HA:/var/data/criorootstorage/overlay/l/474KLOAHJ7WZPJLAVLDGZB5M5R:/var/data/criorootstorage/overlay/l/7BXZAXTWWK4KLF3KDMCMNTELWY:/var/data/criorootstorage/overlay/l/PGC6CX4ZN5OP36DBZG6UDOLWZX:/var/data/criorootstorage/overlay/l/BRTHFRM2FN6GPRZSO5VW76GVZJ,upperdir=/var/data/criorootstorage/overlay/464a4b4fb4984087ead26962959d1553b556b41a5c6187bfdce69ee971638d76/diff,workdir=/var/data/criorootstorage/overlay/464a4b4fb4984087ead26962959d1553b556b41a5c6187bfdce69ee971638d76/work)
proc on /proc type proc (rw,nosuid,nodev,noexec,relatime)
tmpfs on /dev type tmpfs (rw,nosuid,context="system_u:object_r:container_file_t:s0:c409,c725",size=65536k,mode=755)
devpts on /dev/pts type devpts (rw,nosuid,noexec,relatime,context="system_u:object_r:container_file_t:s0:c409,c725",gid=5,mode=620,ptmxmode=666)
mqueue on /dev/mqueue type mqueue (rw,nosuid,nodev,noexec,relatime,seclabel)
sysfs on /sys type sysfs (ro,nosuid,nodev,noexec,relatime,seclabel)
tmpfs on /sys/fs/cgroup type tmpfs (rw,nosuid,nodev,noexec,relatime,context="system_u:object_r:container_file_t:s0:c409,c725",mode=755)
cgroup on /sys/fs/cgroup/systemd type cgroup (ro,nosuid,nodev,noexec,relatime,seclabel,xattr,release_agent=/usr/lib/systemd/systemd-cgroups-agent,name=systemd)
cgroup on /sys/fs/cgroup/perf_event type cgroup (ro,nosuid,nodev,noexec,relatime,seclabel,perf_event)
cgroup on /sys/fs/cgroup/freezer type cgroup (ro,nosuid,nodev,noexec,relatime,seclabel,freezer)
cgroup on /sys/fs/cgroup/devices type cgroup (ro,nosuid,nodev,noexec,relatime,seclabel,devices)
cgroup on /sys/fs/cgroup/cpu,cpuacct type cgroup (ro,nosuid,nodev,noexec,relatime,seclabel,cpuacct,cpu)
cgroup on /sys/fs/cgroup/blkio type cgroup (ro,nosuid,nodev,noexec,relatime,seclabel,blkio)
cgroup on /sys/fs/cgroup/hugetlb type cgroup (ro,nosuid,nodev,noexec,relatime,seclabel,hugetlb)
cgroup on /sys/fs/cgroup/pids type cgroup (ro,nosuid,nodev,noexec,relatime,seclabel,pids)
cgroup on /sys/fs/cgroup/memory type cgroup (ro,nosuid,nodev,noexec,relatime,seclabel,memory)
cgroup on /sys/fs/cgroup/cpuset type cgroup (ro,nosuid,nodev,noexec,relatime,seclabel,cpuset)
cgroup on /sys/fs/cgroup/net_cls,net_prio type cgroup (ro,nosuid,nodev,noexec,relatime,seclabel,net_prio,net_cls)
shm on /dev/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,context="system_u:object_r:container_file_t:s0:c409,c725",size=65536k)
/dev/vdd on /etc/resolv.conf type ext4 (rw,nosuid,nodev,noexec,relatime,seclabel,data=ordered)
/dev/v [...]

2021-09-20 06:01 UTC, ambiknai commented
As per review comments the changes must go here

https://github.com/IBM/ibm-csi-common/blob/f05bd5ec4b3388ef546717ac47d9cd6eafd741e4/pkg/ibmcloudprovider/volume_provider.go#L64

Hence , closing this PR

2021-09-20 06:01 UTC, closed without merging