Fetch region from node info [ Do not merge ]
kubernetes-sigs/ibm-vpc-block-csi-driver pull request #76
Opened 2022-04-22 08:48 UTC by ambiknai

2022-04-27 06:09 UTC, prankulmahajan requested changes

2022-04-27 06:09 UTC, prankulmahajan commented on pkg/ibmcsidriver/controller_helper.go
> +	fmt.Println("createVolumeResponse:", volResp)
Can we remove this or put in logger ?

2022-04-27 06:09 UTC, prankulmahajan commented on pkg/ibmcsidriver/controller_helper_test.go
> +	fmt.Println(actualCSIVolume)
Same. Can we remove this? 
Or else required, put in logger

2022-04-27 06:37 UTC, sameshai commented on go.mod
>  require (
Please changes this later to beta16

2022-04-28 09:07 UTC, ambiknai commented
Closing this PR. Delivering the feature via diff approach here https://github.com/kubernetes-sigs/ibm-vpc-block-csi-driver/pull/78

2022-04-28 09:07 UTC, closed without merging