VolumeLabels for unmanaged clusters
kubernetes-sigs/ibm-vpc-block-csi-driver pull request #87
Opened 2022-06-21 06:32 UTC by sameshai

2022-06-21 11:35 UTC, arahamad requested changes

2022-06-21 15:24 UTC, sameshai commented
**Test results for IKS cluster with tags in custom storage class** 

"{"level":"info","ts":"2022-06-21T15:21:08.359Z","caller":"vpcvolume/list_volumes.go:47","msg":"Equivalent curl command","RequestID":"878fe3ed-bf3b-4a55-b427-0123516bc375","URL":"https://au-syd.private.iaas.cloud.ibm.com/v1/volumes?generation=2&version=2020-07-02","Operation":{"Name":"ListVolumes","Method":"GET","PathPattern":"/v1/volumes"}}
{"level":"info","ts":"2022-06-21T15:21:09.496Z","caller":"provider/get_volume.go:81","msg":"Successfully retrieved volume details from VPC backend","RequestID":"878fe3ed-bf3b-4a55-b427-0123516bc375","VolumeDetails":null}
{"level":"info","ts":"2022-06-21T15:21:09.496Z","caller":"provider/util.go:243","msg":"Volume details are empty","RequestID":"878fe3ed-bf3b-4a55-b427-0123516bc375"}
{"level":"info","ts":"2022-06-21T15:21:09.496Z","caller":"provider/create_volume.go:41","msg":"Basic validation for CreateVolume request... ","RequestID":"878fe3ed-bf3b-4a55-b427-0123516bc375","RequestedVolumeDetails":{"provider":"","volumeType":"ext4","capacity":10,"iops":null,"tier":null,"region":"us-south","az":"au-syd-1","creationTime":"0001-01-01T00:00:00Z","name":"pvc-a29c9306-caf0-4f9c-ad33-4fbdf2adacec","resource_group":{"id":"f6ac46dbf4594c23b34070a642b9f676"},"profile":{"name":"5iops-tier"},"volume_tags":["sam:test"]}}
{"level":"info","ts":"2022-06-21T15:21:09.496Z","caller":"provider/create_volume.go:46","msg":"Successfully validated inputs for CreateVolume request... ","RequestID":"878fe3ed-bf3b-4a55-b427-0123516bc375"}
{"level":"info","ts":"2022-06-21T15:21:09.496Z","caller":"provider/create_volume.go:69","msg":"Calling VPC provider for volume creation...","RequestID":"878fe3ed-bf3b-4a55-b427-0123516bc375"}
{"level":"info","ts":"2022-06-21T15:21:09.496Z","caller":"vpcvolume/create_volume.go:46","msg":"Equivalent curl command and payload details","RequestID":"878fe3ed-bf3b-4a55-b427-0123516bc375","URL":"https://au-syd.private.iaas.cloud.ibm.com/v1/volumes?generation=2&version=2020-07-02","Payload":{"name":"pvc-a29c9306-caf0-4f9c-ad33-4fbdf2adacec","capacity":10,"resource_group":{"id":"f6ac46dbf4594c23b34070a642b9f676"},"user_tags":["sam:test"],"profile":{"name":"5iops-tier"},"zone":{"name":"au-syd-1"}},"Operation":{"Name":"CreateVolume","Method":"POST","PathPattern":"/v1/volumes"}}
2022/06/21 15:21:09 TIME TAKEN BY FUNCTION ListVolumes IS 1.136971118s
2022/06/21 15:21:09 TIME TAKEN BY FUNCTION GetVolumeByName IS 1.137009857s
I0621 15:21:17.479073       1 server.go:151] GRPC call: /csi.v1.Identity/Probe
I0621 15:21:17.479094       1 server.go:152] GRPC request: 
I0621 15:21:17.479129       1 server.go:157] GRPC response: 
2022/06/21 15:21:18 TIME TAKEN BY FUNCTION CreateVolume IS 9.024707446s
{"level":"info","ts":"2022-06-21T15:21:18.521Z","caller":"provider/create_volume.go:81","msg":"Successfully created volume from VPC provider...","RequestID":"878fe3ed-bf3b-4a55-b427-0123516bc375","VolumeDetails":{"href":"https://au-syd.private.iaas.cloud.ibm.com/v1/volumes/r026-25659931-d92f-4797-a369-117583cccd91","id":"r026-25659931-d92f-4797-a369-117583cccd91","name":"pvc-a29c9306-caf0-4f9c-ad33-4fbdf2adacec","capacity":10,"iops":3000,"resource_group":{"href":"https://resource-controller.cloud.ibm.com/v2/resource_groups/f6ac46dbf4594c23b34070a642b9f676","id":"f6ac46dbf4594c23b34070a642b9f676","name":"vpc-ca-storage"},"user_tags":["sam:test"],"profile":{"href":"https://au-syd.private.iaas.cloud.ibm.com/v1/volume/profiles/5iops-tier","name":"5iops-tier"},"created_at":"2022-06-21T15:21:15Z","status":"pending","volume_attachments":[],"zone":{"name":"au-syd-1","href":"https://au-syd.private.iaas.cloud.ibm.com/v1/regions/au-syd/zones/au-syd-1"},"crn":"crn:v1:bluemix:public:is:au-syd-1:a/c468d8824937fecd8a0860fe0f379bf9::volume:r026-25659931-d92f-4797-a369-117583cccd91"}}
{"level":"info","ts":"2022-06-21T15:21:18.521Z","caller":"provider/create_volume.go:83","msg":"Waiting for volume to be in valid (available) state","RequestID":"878fe3ed-bf3b-4a55-b427-0123516bc375","VolumeDetails":{"href":"https://au-syd.private.iaas.cloud.ibm.com/v1/volumes/r026-25659931-d92f-4797-a369-117583cccd91","id":"r026-25659931-d92f-4797-a369-117583cccd91","name":"pvc-a29c9306-caf0-4f9c-ad33-4fbdf2adacec","capacity":10,"iops":3000,"resource_group":{"href":"https://resource-controller.cloud.ibm.com/v2/resource_groups/f6ac46dbf4594c23b34070a642b9f676","id":"f6ac46dbf4594c23b34070a642b9f676","name":"vpc-ca-storage"},"user_tags":["sam:test"],"profile":{"href":"https://au-syd.private.iaas.cloud.ibm.com/v1/volume/profiles/5iops-tier","name":"5iops-tier"},"created_at":"2022-06-21T15:21:15Z","status":"pending","volume_attachments":[],"zone":{"name":"au-syd-1","href":"https://au-syd.private.iaas.cloud.ibm.com/v1/regions/au-syd/zones/au-syd-1"},"crn":"crn:v1:bluemix:public:is:au-syd-1:a/c468d8824937fecd8a0860fe0f379bf9::volume:r026-25659931-d92f-4797-a369-117583cccd91"}}
{"level":"info","ts":"2022-06-21T15:21:18.521Z","caller":"provider/wait_for_valid_volume_state.go:39","msg":"Getting volume details from VPC provider...","RequestID":"878fe3ed-bf3b-4a55-b427-0123516bc375","VolumeID":"r026-25659931-d92f-4797-a369-117583cccd91"}
{"level":"info","ts":"2022-06-21T15:21:18.521Z","caller":"vpcvolume/get_volume.go:46","msg":"Equivalent curl command","RequestID":"878fe3ed-bf3b-4a55-b427-0123516bc375","URL":"https://au-syd.private.iaas.cloud.ibm.com/v1/volumes/%7Bvolume-id%7D?generation=2&version=2020-07-02","Operation":{"Name":"GetVolume","Method":"GET","PathPattern":"/v1/volumes/{volume-id}"}}
2022/06/21 15:21:19 TIME TAKEN BY FUNCTION GetVolume IS 478.653727ms
{"level":"info","ts":"2022-06-21T15:21:19.000Z","caller":"provider/wait_for_valid_volume_state.go:47","msg":"Getting volume details from VPC provider...","RequestID":"878fe3ed-bf3b-4a55-b427-0123516bc375","volume":{"href":"https://au-syd.private.iaas.cloud.ibm.com/v1/volumes/r026-25659931-d92f-4797-a369-117583cccd91","id":"r026-25659931-d92f-4797-a369-117583cccd91","name":"pvc-a29c9306-caf0-4f9c-ad33-4fbdf2adacec","capacity":10,"iops":3000,"resource_group":{"href":"https://resource-controller.cloud.ibm.com/v2/resource_groups/f6ac46dbf4594c23b34070a642b9f676","id":"f6ac46dbf4594c23b34070a642b9f676","name":"vpc-ca-storage"},"profile":{"href":"https://au-syd.private.iaas.cloud.ibm.com/v1/volume/profiles/5iops-tier","name":"5iops-tier"},"created_at":"2022-06-21T15:21:15Z","status":"pending","volume_attachments":[],"zone":{"name":"au-syd-1","href":"https://au-syd.private.iaas.cloud.ibm.com/v1/regions/au-syd/zones/au-syd-1"},"crn":"crn:v1:bluemix:public:is:au-syd-1:a/c468d8824937fecd8a0860fe0f379bf9::volume:r026-25659931-d92f-4797-a369-117583cccd91"}}
I0621 15:21:27.478593       1 server.go:151] GRPC call: /csi.v1.Identity/Probe
I0621 15:21:27.478615       1 server.go:152] GRPC request: 
I0621 15:21:27.478665       1 server.go:157] GRPC response: 
{"level":"info","ts":"2022-06-21T15:21:29.001Z","caller":"vpcvolume/get_volume.go:46","msg":"Equivalent curl command","RequestID":"878fe3ed-bf3b-4a55-b427-0123516bc375","URL":"https://au-syd.private.iaas.cloud.ibm.com/v1/volumes/%7Bvolume-id%7D?generation=2&version=2020-07-02","Operation":{"Name":"GetVolume","Method":"GET","PathPattern":"/v1/volumes/{volume-id}"}}
2022/06/21 15:21:29 TIME TAKEN BY FUNCTION GetVolume IS 576.343345ms
{"level":"info","ts":"2022-06-21T15:21:29.577Z","caller":"provider/wait_for_valid_volume_state.go:47","msg":"Getting volume details from VPC provider...","RequestID":"878fe3ed-bf3b-4a55-b427-0123516bc375","volume":{"href":"https://au-syd.private.iaas.cloud.ibm.com/v1/volumes/r026-25659931-d92f-4797-a369-117583cccd91","id":"r026-25659931-d92f-4797-a369-117583cccd91","name":"pvc-a29c9306-caf0-4f9c-ad33-4fbdf2adacec","capacity":10,"iops":3000,"resource_group":{"href":"https://resource-controller.cloud.ibm.com/v2/resource_groups/f6ac46dbf4594c23b34070a642b9f676","id":"f6ac46dbf4594c23b34070a642b9f676","name":"vpc-ca-storage"},"user_tags":["sam:test"],"profile":{"href":"https://au-syd.private [...]

2022-06-21 15:27 UTC, sameshai commented
**Test results for IKS cluster standard storage class** 

```

```

2022-06-22 05:58 UTC, sameshai commented
**Test results for IPI cluster** 

```
I0622 05:53:33.949317       1 server.go:151] GRPC call: /csi.v1.Controller/CreateVolume
{"level":"info","ts":"2022-06-22T05:53:33.949Z","caller":"ibmcsidriver/controller.go:69","msg":"CSIControllerServer-CreateVolume... ","RequestID":"be041ca9-6751-4f18-975a-dd45bec700c2","Request":{"name":"pvc-3672209f-c5c6-42c6-a44b-1eb07081850a","capacity_range":{"required_bytes":10737418240},"volume_capabilities":[{"AccessType":{"Mount":{"fs_type":"ext4"}},"access_mode":{"mode":1}}],"parameters":{"encrypted":"false","encryptionKey":"","profile":"5iops-tier","region":"","resourceGroup":"","tags":"","zone":""},"accessibility_requirements":{"requisite":[{"segments":{"failure-domain.beta.kubernetes.io/region":"eu-gb","failure-domain.beta.kubernetes.io/zone":"eu-gb-3"}},{"segments":{"failure-domain.beta.kubernetes.io/region":"eu-gb","failure-domain.beta.kubernetes.io/zone":"eu-gb-1"}},{"segments":{"failure-domain.beta.kubernetes.io/region":"eu-gb","failure-domain.beta.kubernetes.io/zone":"eu-gb-2"}}],"preferred":[{"segments":{"failure-domain.beta.kubernetes.io/region":"eu-gb","failure-domain.beta.kubernetes.io/zone":"eu-gb-1"}},{"segments":{"failure-domain.beta.kubernetes.io/region":"eu-gb","failure-domain.beta.kubernetes.io/zone":"eu-gb-2"}},{"segments":{"failure-domain.beta.kubernetes.io/region":"eu-gb","failure-domain.beta.kubernetes.io/zone":"eu-gb-3"}}]}}}
{"level":"info","ts":"2022-06-22T05:53:33.949Z","caller":"ibmcsidriver/controller_helper.go:206","msg":"Volume size in bytes","RequestID":"be041ca9-6751-4f18-975a-dd45bec700c2","capacity":10737418240}
{"level":"info","ts":"2022-06-22T05:53:33.949Z","caller":"ibmcsidriver/controller_helper.go:212","msg":"Volume size in GiB","RequestID":"be041ca9-6751-4f18-975a-dd45bec700c2","capacity":10}
{"level":"info","ts":"2022-06-22T05:53:33.949Z","caller":"ibmcsidriver/controller.go:97","msg":"Volume request after masking encryption key","RequestID":"be041ca9-6751-4f18-975a-dd45bec700c2","Volume":{"provider":"","volumeType":"ext4","capacity":10,"iops":null,"tier":null,"az":"eu-gb-1","creationTime":"0001-01-01T00:00:00Z","name":"pvc-3672209f-c5c6-42c6-a44b-1eb07081850a","resource_group":{"id":"a989c137a1df46eebb42016e43924275"},"encryption_key":{"crn":"********"},"profile":{"name":"5iops-tier"}}}
{"level":"info","ts":"2022-06-22T05:53:33.949Z","caller":"ibmcloudprovider/volume_provider.go:132","msg":"IBMCloudStorageProvider-GetProviderSession...","RequestID":"be041ca9-6751-4f18-975a-dd45bec700c2"}
{"level":"info","ts":"2022-06-22T05:53:33.949Z","caller":"utils/init_provider.go:78","msg":"Fetching provider session","RequestID":"be041ca9-6751-4f18-975a-dd45bec700c2"}
{"level":"info","ts":"2022-06-22T05:53:33.949Z","caller":"utils/init_provider.go:84","msg":"Calling provider/utils/init_provider.go GenerateContextCredentials","RequestID":"be041ca9-6751-4f18-975a-dd45bec700c2"}
{"level":"info","ts":"2022-06-22T05:53:33.949Z","caller":"utils/init_provider.go:103","msg":"Generating generateContextCredentials for ","RequestID":"be041ca9-6751-4f18-975a-dd45bec700c2","Provider ID":"vpc"}
{"level":"info","ts":"2022-06-22T05:53:33.949Z","caller":"utils/init_provider.go:108","msg":"Calling provider/init_provider.go ForIAMAccessToken","RequestID":"be041ca9-6751-4f18-975a-dd45bec700c2"}
{"level":"info","ts":"2022-06-22T05:53:33.949Z","caller":"iam/token_exchange.go:129","msg":"Fetching using secret provider","RequestID":"be041ca9-6751-4f18-975a-dd45bec700c2"}
{"level":"info","timestamp":"2022-06-22T05:53:33.949Z","caller":"secret_provider/unmanaged_secret_provider.go:83","msg":"In GetDefaultIAMToken()","name":"secret-provider","secret-provider-type":"unmanaged-secret-provider"}
{"level":"info","timestamp":"2022-06-22T05:53:33.949Z","caller":"authenticator/api-key.go:57","msg":"Fetching fresh token","name":"secret-provider","secret-provider-type":"unmanaged-secret-provider"}
{"level":"info","timestamp":"2022-06-22T05:53:34.483Z","caller":"authenticator/api-key.go:76","msg":"Fetched fresh iam token","name":"secret-provider","secret-provider-type":"unmanaged-secret-provider","token-life-time-in-seconds":3597}
{"level":"info","ts":"2022-06-22T05:53:34.483Z","caller":"iam/token_exchange.go:135","msg":"Successfully fetched iam token","RequestID":"be041ca9-6751-4f18-975a-dd45bec700c2"}
{"level":"info","ts":"2022-06-22T05:53:34.483Z","caller":"provider/provider.go:177","msg":"Entering OpenSession","RequestID":"be041ca9-6751-4f18-975a-dd45bec700c2"}
{"level":"info","ts":"2022-06-22T05:53:34.483Z","caller":"provider/provider.go:200","msg":"","RequestID":"be041ca9-6751-4f18-975a-dd45bec700c2","apiConfig.ContextID":"be041ca9-6751-4f18-975a-dd45bec700c2 "}
{"level":"info","ts":"2022-06-22T05:53:34.483Z","caller":"metrics/metrics.go:73","msg":"Time to complete","RequestID":"be041ca9-6751-4f18-975a-dd45bec700c2","OpenSession":0.000030427}
{"level":"info","ts":"2022-06-22T05:53:34.483Z","caller":"utils/init_provider.go:97","msg":"Successfully fetched provider session","RequestID":"be041ca9-6751-4f18-975a-dd45bec700c2"}
{"level":"info","ts":"2022-06-22T05:53:34.483Z","caller":"ibmcloudprovider/volume_provider.go:155","msg":"Successfully got the provider session","RequestID":"be041ca9-6751-4f18-975a-dd45bec700c2","ProviderName":"VPC"}
{"level":"info","ts":"2022-06-22T05:53:34.483Z","caller":"provider/get_volume.go:63","msg":"Basic validation for volume Name...","RequestID":"be041ca9-6751-4f18-975a-dd45bec700c2","VolumeName":"pvc-3672209f-c5c6-42c6-a44b-1eb07081850a"}
{"level":"info","ts":"2022-06-22T05:53:34.483Z","caller":"provider/get_volume.go:69","msg":"Getting volume details from VPC provider...","RequestID":"be041ca9-6751-4f18-975a-dd45bec700c2","VolumeName":"pvc-3672209f-c5c6-42c6-a44b-1eb07081850a"}
{"level":"info","ts":"2022-06-22T05:53:34.483Z","caller":"vpcvolume/list_volumes.go:47","msg":"Equivalent curl command","RequestID":"be041ca9-6751-4f18-975a-dd45bec700c2","URL":"https://eu-gb.iaas.cloud.ibm.com/v1/volumes?generation=2&version=2020-07-02","Operation":{"Name":"ListVolumes","Method":"GET","PathPattern":"/v1/volumes"}}
2022/06/22 05:53:35 TIME TAKEN BY FUNCTION ListVolumes IS 1.012710218s
2022/06/22 05:53:35 TIME TAKEN BY FUNCTION GetVolumeByName IS 1.012747164s
{"level":"info","ts":"2022-06-22T05:53:35.496Z","caller":"provider/get_volume.go:81","msg":"Successfully retrieved volume details from VPC backend","RequestID":"be041ca9-6751-4f18-975a-dd45bec700c2","VolumeDetails":null}
{"level":"info","ts":"2022-06-22T05:53:35.496Z","caller":"provider/util.go:243","msg":"Volume details are empty","RequestID":"be041ca9-6751-4f18-975a-dd45bec700c2"}
{"level":"info","ts":"2022-06-22T05:53:35.496Z","caller":"provider/create_volume.go:41","msg":"Basic validation for CreateVolume request... ","RequestID":"be041ca9-6751-4f18-975a-dd45bec700c2","RequestedVolumeDetails":{"provider":"","volumeType":"ext4","capacity":10,"iops":null,"tier":null,"az":"eu-gb-1","creationTime":"0001-01-01T00:00:00Z","name":"pvc-3672209f-c5c6-42c6-a44b-1eb07081850a","resource_group":{"id":"a989c137a1df46eebb42016e43924275"},"profile":{"name":"5iops-tier"}}}
{"level":"info","ts":"2022-06-22T05:53:35.496Z","caller":"provider/create_volume.go:46","msg":"Successfully validated inputs for CreateVolume request... ","RequestID":"be041ca9-6751-4f18-975a-dd45bec700c2"}
{"level":"info","ts":"2022-06-22T05:53:35.496Z","caller":"provider/create_volume.go:69","msg":"Calling VPC provider for volume creation...","RequestID":"be041ca9-6751-4f18-975a-dd45bec700c2"}
{"level":"info","ts":"2022-06-22T05:53:35.496Z","caller":"vpcvolume/create_volume.go:46","msg":"Equivalent curl command and payload details","RequestID":"be041ca9-6751-4f18-975a-dd45bec700c2","URL":"https://eu-gb.iaas.cloud.ibm.com/v1/volumes?generation=2&version=2020-07-02","Payload":{"name":"pvc-3672209f-c5c6-42c6-a44b-1eb07081850a","capacity":10,"resource_group":{"id":"a989c137a1df46eebb42016e43924275"},"user_tags":["kubernetes-io-cluster-sam-ipi-common-swv4z:owned"],"profile":{"name":"5iops- [...]

2022-06-22 06:02 UTC, sameshai commented
**Test results for IPI cluster with custom tagging **

```
{"level":"info","ts":"2022-06-22T05:59:07.280Z","caller":"ibmcsidriver/controller.go:69","msg":"CSIControllerServer-CreateVolume... ","RequestID":"0db9321c-3045-49fa-86dd-05915fc2b658","Request":{"name":"pvc-f754ceeb-b52e-446e-9f60-ea2ff5c29813","capacity_range":{"required_bytes":10737418240},"volume_capabilities":[{"AccessType":{"Mount":{"fs_type":"ext4"}},"access_mode":{"mode":1}}],"parameters":{"billingType":"hourly","classVersion":"1","encrypted":"false","encryptionKey":"","generation":"gc","profile":"5iops-tier","region":"us-south","resourceGroup":"","tags":"sam:test","zone":""},"accessibility_requirements":{"requisite":[{"segments":{"failure-domain.beta.kubernetes.io/region":"eu-gb","failure-domain.beta.kubernetes.io/zone":"eu-gb-3"}},{"segments":{"failure-domain.beta.kubernetes.io/region":"eu-gb","failure-domain.beta.kubernetes.io/zone":"eu-gb-1"}},{"segments":{"failure-domain.beta.kubernetes.io/region":"eu-gb","failure-domain.beta.kubernetes.io/zone":"eu-gb-2"}}],"preferred":[{"segments":{"failure-domain.beta.kubernetes.io/region":"eu-gb","failure-domain.beta.kubernetes.io/zone":"eu-gb-1"}},{"segments":{"failure-domain.beta.kubernetes.io/region":"eu-gb","failure-domain.beta.kubernetes.io/zone":"eu-gb-2"}},{"segments":{"failure-domain.beta.kubernetes.io/region":"eu-gb","failure-domain.beta.kubernetes.io/zone":"eu-gb-3"}}]}}}
{"level":"info","ts":"2022-06-22T05:59:07.280Z","caller":"ibmcsidriver/controller_helper.go:172","msg":"Ignoring storage class parameter","RequestID":"0db9321c-3045-49fa-86dd-05915fc2b658","ClassParameter":"classVersion"}
{"level":"info","ts":"2022-06-22T05:59:07.280Z","caller":"ibmcsidriver/controller_helper.go:176","msg":"Ignoring storage class parameter, for backward compatibility","RequestID":"0db9321c-3045-49fa-86dd-05915fc2b658","ClassParameter":"generation"}
{"level":"info","ts":"2022-06-22T05:59:07.280Z","caller":"ibmcsidriver/controller_helper.go:206","msg":"Volume size in bytes","RequestID":"0db9321c-3045-49fa-86dd-05915fc2b658","capacity":10737418240}
{"level":"info","ts":"2022-06-22T05:59:07.280Z","caller":"ibmcsidriver/controller_helper.go:212","msg":"Volume size in GiB","RequestID":"0db9321c-3045-49fa-86dd-05915fc2b658","capacity":10}
{"level":"info","ts":"2022-06-22T05:59:07.280Z","caller":"ibmcsidriver/controller.go:97","msg":"Volume request after masking encryption key","RequestID":"0db9321c-3045-49fa-86dd-05915fc2b658","Volume":{"provider":"","volumeType":"ext4","capacity":10,"iops":null,"tier":null,"region":"us-south","az":"eu-gb-1","creationTime":"0001-01-01T00:00:00Z","name":"pvc-f754ceeb-b52e-446e-9f60-ea2ff5c29813","resource_group":{"id":"a989c137a1df46eebb42016e43924275"},"encryption_key":{"crn":"********"},"profile":{"name":"5iops-tier"},"volume_tags":["sam:test"]}}
{"level":"info","ts":"2022-06-22T05:59:07.280Z","caller":"ibmcloudprovider/volume_provider.go:132","msg":"IBMCloudStorageProvider-GetProviderSession...","RequestID":"0db9321c-3045-49fa-86dd-05915fc2b658"}
{"level":"info","ts":"2022-06-22T05:59:07.280Z","caller":"utils/init_provider.go:78","msg":"Fetching provider session","RequestID":"0db9321c-3045-49fa-86dd-05915fc2b658"}
{"level":"info","ts":"2022-06-22T05:59:07.280Z","caller":"utils/init_provider.go:84","msg":"Calling provider/utils/init_provider.go GenerateContextCredentials","RequestID":"0db9321c-3045-49fa-86dd-05915fc2b658"}
{"level":"info","ts":"2022-06-22T05:59:07.280Z","caller":"utils/init_provider.go:103","msg":"Generating generateContextCredentials for ","RequestID":"0db9321c-3045-49fa-86dd-05915fc2b658","Provider ID":"vpc"}
{"level":"info","ts":"2022-06-22T05:59:07.280Z","caller":"utils/init_provider.go:108","msg":"Calling provider/init_provider.go ForIAMAccessToken","RequestID":"0db9321c-3045-49fa-86dd-05915fc2b658"}
{"level":"info","ts":"2022-06-22T05:59:07.280Z","caller":"iam/token_exchange.go:129","msg":"Fetching using secret provider","RequestID":"0db9321c-3045-49fa-86dd-05915fc2b658"}
{"level":"info","timestamp":"2022-06-22T05:59:07.280Z","caller":"secret_provider/unmanaged_secret_provider.go:83","msg":"In GetDefaultIAMToken()","name":"secret-provider","secret-provider-type":"unmanaged-secret-provider"}
{"level":"info","timestamp":"2022-06-22T05:59:07.280Z","caller":"authenticator/api-key.go:57","msg":"Fetching fresh token","name":"secret-provider","secret-provider-type":"unmanaged-secret-provider"}
{"level":"info","timestamp":"2022-06-22T05:59:07.856Z","caller":"authenticator/api-key.go:76","msg":"Fetched fresh iam token","name":"secret-provider","secret-provider-type":"unmanaged-secret-provider","token-life-time-in-seconds":3597}
{"level":"info","ts":"2022-06-22T05:59:07.856Z","caller":"iam/token_exchange.go:135","msg":"Successfully fetched iam token","RequestID":"0db9321c-3045-49fa-86dd-05915fc2b658"}
{"level":"info","ts":"2022-06-22T05:59:07.856Z","caller":"provider/provider.go:177","msg":"Entering OpenSession","RequestID":"0db9321c-3045-49fa-86dd-05915fc2b658"}
{"level":"info","ts":"2022-06-22T05:59:07.856Z","caller":"provider/provider.go:200","msg":"","RequestID":"0db9321c-3045-49fa-86dd-05915fc2b658","apiConfig.ContextID":"0db9321c-3045-49fa-86dd-05915fc2b658 "}
{"level":"info","ts":"2022-06-22T05:59:07.857Z","caller":"metrics/metrics.go:73","msg":"Time to complete","RequestID":"0db9321c-3045-49fa-86dd-05915fc2b658","OpenSession":0.000026664}
{"level":"info","ts":"2022-06-22T05:59:07.857Z","caller":"utils/init_provider.go:97","msg":"Successfully fetched provider session","RequestID":"0db9321c-3045-49fa-86dd-05915fc2b658"}
{"level":"info","ts":"2022-06-22T05:59:07.857Z","caller":"ibmcloudprovider/volume_provider.go:155","msg":"Successfully got the provider session","RequestID":"0db9321c-3045-49fa-86dd-05915fc2b658","ProviderName":"VPC"}
{"level":"info","ts":"2022-06-22T05:59:07.857Z","caller":"provider/get_volume.go:63","msg":"Basic validation for volume Name...","RequestID":"0db9321c-3045-49fa-86dd-05915fc2b658","VolumeName":"pvc-f754ceeb-b52e-446e-9f60-ea2ff5c29813"}
{"level":"info","ts":"2022-06-22T05:59:07.857Z","caller":"provider/get_volume.go:69","msg":"Getting volume details from VPC provider...","RequestID":"0db9321c-3045-49fa-86dd-05915fc2b658","VolumeName":"pvc-f754ceeb-b52e-446e-9f60-ea2ff5c29813"}
{"level":"info","ts":"2022-06-22T05:59:07.857Z","caller":"vpcvolume/list_volumes.go:47","msg":"Equivalent curl command","RequestID":"0db9321c-3045-49fa-86dd-05915fc2b658","URL":"https://eu-gb.iaas.cloud.ibm.com/v1/volumes?generation=2&version=2020-07-02","Operation":{"Name":"ListVolumes","Method":"GET","PathPattern":"/v1/volumes"}}
I0622 05:59:07.881316       1 server.go:151] GRPC call: /csi.v1.Identity/Probe
2022/06/22 05:59:09 TIME TAKEN BY FUNCTION ListVolumes IS 1.234288555s
2022/06/22 05:59:09 TIME TAKEN BY FUNCTION GetVolumeByName IS 1.234322238s
{"level":"info","ts":"2022-06-22T05:59:09.091Z","caller":"provider/get_volume.go:81","msg":"Successfully retrieved volume details from VPC backend","RequestID":"0db9321c-3045-49fa-86dd-05915fc2b658","VolumeDetails":null}
{"level":"info","ts":"2022-06-22T05:59:09.091Z","caller":"provider/util.go:243","msg":"Volume details are empty","RequestID":"0db9321c-3045-49fa-86dd-05915fc2b658"}
{"level":"info","ts":"2022-06-22T05:59:09.091Z","caller":"provider/create_volume.go:41","msg":"Basic validation for CreateVolume request... ","RequestID":"0db9321c-3045-49fa-86dd-05915fc2b658","RequestedVolumeDetails":{"provider":"","volumeType":"ext4","capacity":10,"iops":null,"tier":null,"region":"us-south","az":"eu-gb-1","creationTime":"0001-01-01T00:00:00Z","name":"pvc-f754ceeb-b52e-446e-9f60-ea2ff5c29813","resource_group":{"id":"a989c137a1df46eebb42016e43924275"},"profile":{"name":"5iops-tier"},"volume_tags":["sam:test"]}}
{"level":"info","ts":"2022-06-22T05:59:09.091Z","caller":"provider/create_volume.go:46","msg":"Successfully validated inputs for CreateVolume request... ","RequestID":"0db9321c-3045-49fa-86dd-05915fc2b658"}
{"level":"info","ts":"2022-06-22T05:59:09 [...]

2022-06-22 06:20 UTC, GunaKKIBM approved these changes

2022-06-22 08:24 UTC, ambiknai commented
/ok-to-test

2022-06-22 09:13 UTC, ambiknai approved these changes

2022-06-22 09:24 UTC, arahamad approved these changes
/lgtm

2022-06-22 09:25 UTC, merged